In [16]:
print("AdventureWorks Analytics - Python is working!")

AdventureWorks Analytics - Python is working!

In [17]:
import pandas as pd 
print("Pandas imported successfully!")

Pandas imported successfully!

In [18]:
from pathlib import Path
print(Path.cwd())

c:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\notebooks

In [19]:
from pathlib import Path
data_path = Path("../data")
print(data_path.resolve())

C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data

In [20]:
csv_files = list(data_path.glob("*.csv"))
for file in csv_files:
    print(file.name)

In [21]:
customers = pd.read_csv(data_path / "customers.csv")
print("Customers Table Loaded Successfully!")

FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\customers.csv'

In [ ]:
customers.head()

,CustomerKey,Prefix,FirstName,LastName,BirthDate,Unnamed: 5,MaritalStatus,Gender,EmailAddress,AnnualIncome,TotalChildren,EducationLevel,Occupation,HomeOwner
0,11000,MR.,JON,YANG,04/08/1966,NaN,M,M,jon24@learnsector.com,"$90,000",2,Bachelors,Professional,Y
1,11001,MR.,EUGENE,HUANG,14/05/1965,NaN,S,M,eugene10@learnsector.com,"$60,000",3,Bachelors,Professional,N
2,11002,MR.,RUBEN,TORRES,08/12/1965,NaN,M,M,ruben35@learnsector.com,"$60,000",3,Bachelors,Professional,Y
3,11003,MS.,CHRISTY,ZHU,15/02/1968,NaN,S,F,christy12@learnsector.com,"$70,000",0,Bachelors,Professional,N
4,11004,MRS.,ELIZABETH,JOHNSON,08/08/1968,NaN,S,F,elizabeth5@learnsector.com,"$80,000",5,Bachelors,Professional,Y

In [ ]:
customers.shape

(18148, 14)

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18148 entries, 0 to 18147
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerKey     18148 non-null  int64
 1   Prefix          18018 non-null  object
 2   FirstName       18148 non-null  object
 3   LastName        18148 non-null  object
 4   BirthDate       18148 non-null  object
 5   Unnamed: 5      0 non-null      float64
 6   MaritalStatus   18148 non-null  object
 7   Gender          18018 non-null  object
 8   EmailAddress    18148 non-null  object
 9   AnnualIncome    18148 non-null  object
 10  TotalChildren   18148 non-null  int64
 11  EducationLevel  18148 non-null  object
 12  Occupation      18148 non-null  object
 13  HomeOwner       18148 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 1.9+ MB

In [ ]:
customers.isna().sum()

CustomerKey           0
Prefix              130
FirstName             0
LastName              0
BirthDate             0
Unnamed: 5        18148
MaritalStatus         0
Gender              130
EmailAddress          0
AnnualIncome          0
TotalChildren         0
EducationLevel        0
Occupation            0
HomeOwner             0
dtype: int64

In [ ]:
customers[customers["Prefix"].isna()][["CustomerKey","Prefix","FirstName","LastName","Gender"]].head(10)

      CustomerKey Prefix  FirstName   LastName Gender
24          11025    NaN  ALEJANDRO       BECK    NaN
34          11035    NaN      WENDY  DOMINGUEZ    NaN
81          11082    NaN     ANGELA     BUTLER    NaN
228         11234    NaN       ANNA    GRIFFIN    NaN
464         11475    NaN      CESAR     SUBRAM    NaN
512         11526    NaN  KATHERINE       DIAZ    NaN
608         11623    NaN     ANGELA      PERRY    NaN
627         11643    NaN      NAOMI      MUNOZ    NaN
944         11965    NaN      KATIE        SHE    NaN
1254        12276    NaN     ALISHA       SHAN    NaN

In [ ]:
print("BirthDate data type :", customers["BirthDate"].dtype)
print("AnnualIncome data type :", customers["AnnualIncome"].dtype)

print("\nSample BirthDate values :")
print(customers["BirthDate"].head())


print("\nSample AnnualIncome values :")
print(customers["AnnualIncome"].head())

BirthDate data type : object
AnnualIncome data type : object

Sample BirthDate values :
0    04/08/1966
1    14/05/1965
2    08/12/1965
3    15/02/1968
4    08/08/1968
Name: BirthDate, dtype: object

Sample AnnualIncome values :
0    $90,000
1    $60,000
2    $60,000
3    $70,000
4    $80,000
Name: AnnualIncome, dtype: object

In [ ]:
print("Total rows :",len(customers))
print("Unique CustomerKeys :",customers["CustomerKey"].nunique())
print("Duplicate CustomerKeys :",customers["CustomerKey"].duplicated().sum())

Total rows : 18148
Unique CustomerKeys : 18148
Duplicate CustomerKeys : 0

In [ ]:
print("Minimum Income :",customers["AnnualIncome"].min())
print("Maximum Income :",customers["AnnualIncome"].max())
print("\nUnique Income Values :",customers["AnnualIncome"].nunique())

Minimum Income : $10,000
Maximum Income : $90,000

Unique Income Values : 16

In [ ]:
sorted(customers["AnnualIncome"].unique())

['$10,000 ',
 '$100,000 ',
 '$110,000 ',
 '$120,000 ',
 '$130,000 ',
 '$150,000 ',
 '$160,000 ',
 '$170,000 ',
 '$20,000 ',
 '$30,000 ',
 '$40,000 ',
 '$50,000 ',
 '$60,000 ',
 '$70,000 ',
 '$80,000 ',
 '$90,000 ']

In [ ]:
customers["AnnualIncome"].unique()

array(['$90,000 ', '$60,000 ', '$70,000 ', '$80,000 ', '$100,000 ',
       '$30,000 ', '$20,000 ', '$40,000 ', '$10,000 ', '$160,000 ',
       '$170,000 ', '$120,000 ', '$130,000 ', '$110,000 ', '$150,000 ',
       '$50,000 '], dtype=object)

In [ ]:
customers["AnnualIncome"] = customers["AnnualIncome"].str.replace("$","", regex = False).str.replace(",","", regex = False).str.strip().astype(int)

In [ ]:
customers["AnnualIncome"].dtype

dtype('int64')

In [ ]:
customers["AnnualIncome"].describe()

count     18148.000000
mean      57269.120564
std       32236.535573
min       10000.000000
25%       30000.000000
50%       60000.000000
75%       70000.000000
max      170000.000000
Name: AnnualIncome, dtype: float64

In [ ]:
customers["AnnualIncome"].head()

0    90000
1    60000
2    60000
3    70000
4    80000
Name: AnnualIncome, dtype: int64

In [ ]:
customers["AnnualIncome"].unique()

array([ 90000,  60000,  70000,  80000, 100000,  30000,  20000,  40000,
        10000, 160000, 170000, 120000, 130000, 110000, 150000,  50000])

In [ ]:
customers = customers.drop(columns = ["Unnamed: 5"])

In [ ]:
customers.shape

(18148, 13)

In [ ]:
print("Shape :", customers.shape)
print("\nMissing Values :\n", customers.isna().sum())

print("\nColumns :")
print(customers.columns.tolist)

Shape : (18148, 13)

Missing Values :
 CustomerKey         0
Prefix            130
FirstName           0
LastName            0
BirthDate           0
MaritalStatus       0
Gender            130
EmailAddress        0
AnnualIncome        0
TotalChildren       0
EducationLevel      0
Occupation          0
HomeOwner           0
dtype: int64

Columns :
<bound method IndexOpsMixin.tolist of Index(['CustomerKey', 'Prefix', 'FirstName', 'LastName', 'BirthDate',
       'MaritalStatus', 'Gender', 'EmailAddress', 'AnnualIncome',
       'TotalChildren', 'EducationLevel', 'Occupation', 'HomeOwner'],
      dtype='object')>

In [ ]:
customers["BirthDate"] = pd.to_datetime(customers["BirthDate"], format = "%d/%m/%Y")

In [ ]:
print(customers["BirthDate"].dtype)
print(customers["BirthDate"].head())

datetime64[ns]
0   1966-08-04
1   1965-05-14
2   1965-12-08
3   1968-02-15
4   1968-08-08
Name: BirthDate, dtype: datetime64[ns]

In [ ]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18148 entries, 0 to 18147
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerKey     18148 non-null  int64
 1   Prefix          18018 non-null  object
 2   FirstName       18148 non-null  object
 3   LastName        18148 non-null  object
 4   BirthDate       18148 non-null  datetime64[ns]
 5   MaritalStatus   18148 non-null  object
 6   Gender          18018 non-null  object
 7   EmailAddress    18148 non-null  object
 8   AnnualIncome    18148 non-null  int64
 9   TotalChildren   18148 non-null  int64
 10  EducationLevel  18148 non-null  object
 11  Occupation      18148 non-null  object
 12  HomeOwner       18148 non-null  object
dtypes: datetime64[ns](1), int64(3), object(9)
memory usage: 1.8+ MB

In [ ]:
duplicate_rows = customers.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

Duplicate rows: 0

In [ ]:
categorical_columns = [
    "Prefix",
    "MaritalStatus",
    "Gender",
    "EducationLevel",
    "Occupation",
    "HomeOwner"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(customers[column].value_counts(dropna=False))

--- Prefix ---
Prefix
MR.     9126
MRS.    6422
MS.     2470
NaN      130
Name: count, dtype: int64

--- MaritalStatus ---
MaritalStatus
M    9817
S    8331
Name: count, dtype: int64

--- Gender ---
Gender
M      9126
F      8892
NaN     130
Name: count, dtype: int64

--- EducationLevel ---
EducationLevel
Bachelors              5261
Partial College        4966
High School            3241
Graduate Degree        3125
Partial High School    1555
Name: count, dtype: int64

--- Occupation ---
Occupation
Professional      5424
Skilled Manual    4501
Management        3011
Clerical          2859
Manual            2353
Name: count, dtype: int64

--- HomeOwner ---
HomeOwner
Y    12260
N     5888
Name: count, dtype: int64

In [ ]:
numeric_columns = [
    "CustomerKey",
    "AnnualIncome",
    "TotalChildren"
]

for column in numeric_columns:
    print(f"\n--- {column} ---")
    print(customers[column].describe())

--- CustomerKey ---
count    18148.000000
mean     20247.470465
std       5336.245656
min      11000.000000
25%      15626.750000
50%      20252.500000
75%      24868.250000
max      29483.000000
Name: CustomerKey, dtype: float64

--- AnnualIncome ---
count     18148.000000
mean      57269.120564
std       32236.535573
min       10000.000000
25%       30000.000000
50%       60000.000000
75%       70000.000000
max      170000.000000
Name: AnnualIncome, dtype: float64

--- TotalChildren ---
count    18148.000000
mean         1.843619
std          1.613203
min          0.000000
25%          0.000000
50%          2.000000
75%          3.000000
max          5.000000
Name: TotalChildren, dtype: float64

In [ ]:
print("Minimum TotalChildren:", customers["TotalChildren"].min())
print("Maximum TotalChildren:", customers["TotalChildren"].max())

print("\nUnique TotalChildren values:")
print(sorted(customers["TotalChildren"].unique()))

Minimum TotalChildren: 0
Maximum TotalChildren: 5

Unique TotalChildren values:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]

In [ ]:
print("Minimum AnnualIncome:", customers["AnnualIncome"].min())
print("Maximum AnnualIncome:", customers["AnnualIncome"].max())

print("\nUnique AnnualIncome values:")
print(sorted(customers["AnnualIncome"].unique()))

Minimum AnnualIncome: 10000
Maximum AnnualIncome: 170000

Unique AnnualIncome values:
[np.int64(10000), np.int64(20000), np.int64(30000), np.int64(40000), np.int64(50000), np.int64(60000), np.int64(70000), np.int64(80000), np.int64(90000), np.int64(100000), np.int64(110000), np.int64(120000), np.int64(130000), np.int64(150000), np.int64(160000), np.int64(170000)]

In [ ]:
print("Missing CustomerKeys:", customers["CustomerKey"].isna().sum())
print("Unique CustomerKeys:", customers["CustomerKey"].nunique())
print("Total customer rows:", len(customers))

Missing CustomerKeys: 0
Unique CustomerKeys: 18148
Total customer rows: 18148

In [ ]:
from pathlib import Path

raw_path = Path("../data/raw")
cleaned_path = Path("../data/cleaned")

raw_path.mkdir(exist_ok=True)
cleaned_path.mkdir(exist_ok=True)

print("Raw data folder:", raw_path.resolve())
print("Cleaned data folder:", cleaned_path.resolve())

Raw data folder: C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\raw
Cleaned data folder: C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned

In [ ]:
import shutil

for file in data_path.glob("*.csv"):
    destination = raw_path / file.name
    shutil.move(file, destination)

print("All raw CSV files moved successfully.")

All raw CSV files moved successfully.

In [ ]:
raw_csv_files = list(raw_path.glob("*.csv"))

print("Number of raw CSV files:", len(raw_csv_files))

for file in sorted(raw_csv_files):
    print(file.name)

Number of raw CSV files: 10
Calendar.csv
Customers.csv
Product-Categories.csv
Product-Subcategories.csv
Products.csv
Returns.csv
Sales-2016.csv
Sales-2017.csv
Sales2015.csv
Territories.csv

In [ ]:
cleaned_customers_file = cleaned_path / "Customers_Cleaned.csv"

customers.to_csv(cleaned_customers_file, index=False)

print("Cleaned Customers file saved to:")
print(cleaned_customers_file.resolve())

Cleaned Customers file saved to:
C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned\Customers_Cleaned.csv

In [ ]:
cleaned_customers = pd.read_csv(cleaned_path / "Customers_Cleaned.csv")

print("Shape:", cleaned_customers.shape)

print("\nColumns:")
print(cleaned_customers.columns.tolist())

print("\nData types:")
print(cleaned_customers.dtypes)

Shape: (18148, 13)

Columns:
['CustomerKey', 'Prefix', 'FirstName', 'LastName', 'BirthDate', 'MaritalStatus', 'Gender', 'EmailAddress', 'AnnualIncome', 'TotalChildren', 'EducationLevel', 'Occupation', 'HomeOwner']

Data types:
CustomerKey        int64
Prefix            object
FirstName         object
LastName          object
BirthDate         object
MaritalStatus     object
Gender            object
EmailAddress      object
AnnualIncome       int64
TotalChildren      int64
EducationLevel    object
Occupation        object
HomeOwner         object
dtype: object

In [ ]:
products = pd.read_csv(raw_path / "Products.csv")

print("Shape:", products.shape)

print("\nColumns:")
print(products.columns.tolist())

print("\nData types:")
print(products.dtypes)

Shape: (293, 11)

Columns:
['ProductKey', 'ProductSubcategoryKey', 'ProductSKU', 'ProductName', 'ModelName', 'ProductDescription', 'ProductColor', 'ProductSize', 'ProductStyle', 'ProductCost', 'ProductPrice']

Data types:
ProductKey                 int64
ProductSubcategoryKey      int64
ProductSKU                object
ProductName               object
ModelName                 object
ProductDescription        object
ProductColor              object
ProductSize               object
ProductStyle              object
ProductCost              float64
ProductPrice             float64
dtype: object

In [ ]:
print("Missing values in Products:")
print(products.isna().sum())

Missing values in Products:
ProductKey                0
ProductSubcategoryKey     0
ProductSKU                0
ProductName               0
ModelName                 0
ProductDescription        0
ProductColor             50
ProductSize               0
ProductStyle              0
ProductCost               0
ProductPrice              0
dtype: int64

In [ ]:
missing_color = products[products["ProductColor"].isna()]

print("Products with missing color:", len(missing_color))

print("\nSample records:")
print(
    missing_color[
        ["ProductKey", "ProductName", "ModelName", "ProductSize", "ProductPrice"]
    ].head(10)
)

Products with missing color: 50

Sample records:
     ProductKey             ProductName               ModelName ProductSize  \
95          391                 LL Fork                 LL Fork           0
96          392                 ML Fork                 ML Fork           0
97          393                 HL Fork                 HL Fork           0
98          394              LL Headset              LL Headset           0
99          395              ML Headset              ML Headset           0
100         396              HL Headset              HL Headset           0
101         397  LL Mountain Handlebars  LL Mountain Handlebars           0
102         399  ML Mountain Handlebars  ML Mountain Handlebars           0
103         401  HL Mountain Handlebars  HL Mountain Handlebars           0
104         403      LL Road Handlebars      LL Road Handlebars           0

     ProductPrice
95       148.2200
96       175.4900
97       229.4900
98        34.2000
99       102.2900
100      124.7300
101       40.4909
102       56.2909
103      109.3364
104       40.4909

In [ ]:
print(
    missing_color["ProductSize"].value_counts(dropna=False)
)

ProductSize
0    50
Name: count, dtype: int64

In [ ]:
print(
    missing_color["ProductName"].to_string(index=False)
)

                     LL Fork
                     ML Fork
                     HL Fork
                  LL Headset
                  ML Headset
                  HL Headset
      LL Mountain Handlebars
      ML Mountain Handlebars
      HL Mountain Handlebars
          LL Road Handlebars
          ML Road Handlebars
          HL Road Handlebars
                  Cable Lock
                    Minipump
               Mountain Pump
Taillights - Battery-Powered
      Headlights - Dual-Beam
   Headlights - Weatherproof
       Water Bottle - 30 oz.
        Mountain Bottle Cage
            Road Bottle Cage
         Patch Kit/8 Patches
         Hitch Rack - 4-Bike
       Bike Wash - Dissolver
       Fender Set - Mountain
      All-Purpose Bike Stand
     LL Mountain Seat/Saddle
     ML Mountain Seat/Saddle
     HL Mountain Seat/Saddle
         LL Road Seat/Saddle
         ML Road Seat/Saddle
         HL Road Seat/Saddle
      LL Touring Seat/Saddle
      ML Touring Seat/Saddle
      HL Touring Seat/Saddle
          Mountain Tire Tube
              Road Tire Tube
           Touring Tire Tube
            LL Mountain Tire
            ML Mountain Tire
            HL Mountain Tire
                LL Road Tire
                ML Road Tire
                HL Road Tire
                Touring Tire
       LL Touring Handlebars
       HL Touring Handlebars
           LL Bottom Bracket
           ML Bottom Bracket
           HL Bottom Bracket

In [ ]:
products["ProductColor"] = products["ProductColor"].fillna("Not Applicable")

In [ ]:
print(products["ProductColor"].value_counts(dropna=False))

ProductColor
Black             88
Not Applicable    50
Red               37
Silver            36
Yellow            36
Blue              26
Multi              8
Silver/Black       7
White              4
Grey               1
Name: count, dtype: int64

In [ ]:
print("Missing ProductKeys:", products["ProductKey"].isna().sum())
print("Unique ProductKeys:", products["ProductKey"].nunique())
print("Total product rows:", len(products))
print("Duplicate ProductKeys:", products["ProductKey"].duplicated().sum())

Missing ProductKeys: 0
Unique ProductKeys: 293
Total product rows: 293
Duplicate ProductKeys: 0

In [ ]:
print("Missing ProductSubcategoryKeys:",
      products["ProductSubcategoryKey"].isna().sum())

print("Unique ProductSubcategoryKeys:",
      products["ProductSubcategoryKey"].nunique())

print("\nProductSubcategoryKey values:")
print(sorted(products["ProductSubcategoryKey"].unique()))

Missing ProductSubcategoryKeys: 0
Unique ProductSubcategoryKeys: 37

ProductSubcategoryKey values:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37)]

In [ ]:
print("ProductCost")
print("Minimum:", products["ProductCost"].min())
print("Maximum:", products["ProductCost"].max())
print("Missing:", products["ProductCost"].isna().sum())

print("\nProductPrice")
print("Minimum:", products["ProductPrice"].min())
print("Maximum:", products["ProductPrice"].max())
print("Missing:", products["ProductPrice"].isna().sum())

ProductCost
Minimum: 0.8565
Maximum: 2171.2942
Missing: 0

ProductPrice
Minimum: 2.29
Maximum: 3578.27
Missing: 0

In [ ]:
print(
    "Products where ProductPrice < ProductCost:",
    (products["ProductPrice"] < products["ProductCost"]).sum()
)

Products where ProductPrice < ProductCost: 0

In [ ]:
duplicate_products = products.duplicated().sum()

print("Duplicate product rows:", duplicate_products)

Duplicate product rows: 0

In [ ]:
cleaned_products_file = cleaned_path / "Products_Cleaned.csv"

products.to_csv(cleaned_products_file, index=False)

print("Cleaned Products file saved to:")
print(cleaned_products_file.resolve())

Cleaned Products file saved to:
C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned\Products_Cleaned.csv

In [ ]:
cleaned_products = pd.read_csv(
    cleaned_path / "Products_Cleaned.csv"
)

print("Shape:", cleaned_products.shape)

print("\nMissing ProductColor values:",
      cleaned_products["ProductColor"].isna().sum())

print("\nProductColor categories:")
print(cleaned_products["ProductColor"].value_counts())

Shape: (293, 11)

Missing ProductColor values: 0

ProductColor categories:
ProductColor
Black             88
Not Applicable    50
Red               37
Silver            36
Yellow            36
Blue              26
Multi              8
Silver/Black       7
White              4
Grey               1
Name: count, dtype: int64

In [ ]:
subcategories = pd.read_csv(
    raw_path / "Product-Subcategories.csv"
)

print("Shape:", subcategories.shape)

print("\nColumns:")
print(subcategories.columns.tolist())

print("\nData types:")
print(subcategories.dtypes)

Shape: (37, 3)

Columns:
['ProductSubcategoryKey', 'SubcategoryName', 'ProductCategoryKey']

Data types:
ProductSubcategoryKey     int64
SubcategoryName          object
ProductCategoryKey        int64
dtype: object

In [ ]:
print("Missing ProductSubcategoryKey:",
      subcategories["ProductSubcategoryKey"].isna().sum())

print("Unique ProductSubcategoryKeys:",
      subcategories["ProductSubcategoryKey"].nunique())

print("Duplicate ProductSubcategoryKeys:",
      subcategories["ProductSubcategoryKey"].duplicated().sum())

print("\nProduct Category Keys:")
print(subcategories["ProductCategoryKey"].value_counts().sort_index())

print("\nDuplicate entire rows:",
      subcategories.duplicated().sum())

Missing ProductSubcategoryKey: 0
Unique ProductSubcategoryKeys: 37
Duplicate ProductSubcategoryKeys: 0

Product Category Keys:
ProductCategoryKey
1     3
2    14
3     8
4    12
Name: count, dtype: int64

Duplicate entire rows: 0

In [ ]:
print("Missing SubcategoryName:",
      subcategories["SubcategoryName"].isna().sum())

print("Unique SubcategoryName:",
      subcategories["SubcategoryName"].nunique())

print("\nSubcategory names:")
print(subcategories["SubcategoryName"].sort_values().to_string(index=False))

Missing SubcategoryName: 0
Unique SubcategoryName: 37

Subcategory names:
       Bib-Shorts
       Bike Racks
      Bike Stands
Bottles and Cages
  Bottom Brackets
           Brakes
             Caps
           Chains
         Cleaners
        Cranksets
      Derailleurs
          Fenders
            Forks
           Gloves
       Handlebars
         Headsets
          Helmets
  Hydration Packs
          Jerseys
           Lights
            Locks
   Mountain Bikes
  Mountain Frames
         Panniers
           Pedals
            Pumps
       Road Bikes
      Road Frames
          Saddles
           Shorts
            Socks
           Tights
  Tires and Tubes
    Touring Bikes
   Touring Frames
            Vests
           Wheels

In [ ]:
subcategories["SubcategoryName"] = (
    subcategories["SubcategoryName"]
    .str.strip()
)

print("Subcategory names after cleaning:")
print(subcategories["SubcategoryName"].sort_values().to_string(index=False))

Subcategory names after cleaning:
       Bib-Shorts
       Bike Racks
      Bike Stands
Bottles and Cages
  Bottom Brackets
           Brakes
             Caps
           Chains
         Cleaners
        Cranksets
      Derailleurs
          Fenders
            Forks
           Gloves
       Handlebars
         Headsets
          Helmets
  Hydration Packs
          Jerseys
           Lights
            Locks
   Mountain Bikes
  Mountain Frames
         Panniers
           Pedals
            Pumps
       Road Bikes
      Road Frames
          Saddles
           Shorts
            Socks
           Tights
  Tires and Tubes
    Touring Bikes
   Touring Frames
            Vests
           Wheels

In [ ]:
for name in subcategories["SubcategoryName"].head(10):
    print(repr(name))

'Mountain Bikes'
'Road Bikes'
'Touring Bikes'
'Handlebars'
'Bottom Brackets'
'Brakes'
'Chains'
'Cranksets'
'Derailleurs'
'Forks'

In [ ]:
cleaned_subcategories_file = (
    cleaned_path / "Product-Subcategories_Cleaned.csv"
)

subcategories.to_csv(
    cleaned_subcategories_file,
    index=False
)

print("Cleaned Product Subcategories file saved to:")
print(cleaned_subcategories_file.resolve())

Cleaned Product Subcategories file saved to:
C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned\Product-Subcategories_Cleaned.csv

In [ ]:
cleaned_subcategories = pd.read_csv(
    cleaned_path / "Product-Subcategories_Cleaned.csv"
)

print("Shape:", cleaned_subcategories.shape)

print("\nMissing SubcategoryName:",
      cleaned_subcategories["SubcategoryName"].isna().sum())

print("\nDuplicate ProductSubcategoryKeys:",
      cleaned_subcategories["ProductSubcategoryKey"].duplicated().sum())

print("\nFirst 5 rows:")
print(cleaned_subcategories.head())

Shape: (37, 3)

Missing SubcategoryName: 0

Duplicate ProductSubcategoryKeys: 0

First 5 rows:
   ProductSubcategoryKey  SubcategoryName  ProductCategoryKey
0                      1   Mountain Bikes                   1
1                      2       Road Bikes                   1
2                      3    Touring Bikes                   1
3                      4       Handlebars                   2
4                      5  Bottom Brackets                   2

In [ ]:
categories = pd.read_csv(
    raw_path / "Product-Categories.csv"
)

print("Shape:", categories.shape)

print("\nColumns:")
print(categories.columns.tolist())

print("\nData types:")
print(categories.dtypes)

Shape: (4, 2)

Columns:
['ProductCategoryKey', 'CategoryName']

Data types:
ProductCategoryKey     int64
CategoryName          object
dtype: object

In [ ]:
print("Missing ProductCategoryKey:",
      categories["ProductCategoryKey"].isna().sum())

print("Unique ProductCategoryKeys:",
      categories["ProductCategoryKey"].nunique())

print("Duplicate ProductCategoryKeys:",
      categories["ProductCategoryKey"].duplicated().sum())

print("\nDuplicate entire rows:",
      categories.duplicated().sum())

print("\nCategory names:")
print(categories["CategoryName"].to_string(index=False))

Missing ProductCategoryKey: 0
Unique ProductCategoryKeys: 4
Duplicate ProductCategoryKeys: 0

Duplicate entire rows: 0

Category names:
      Bikes
 Components
   Clothing
Accessories

In [ ]:
cleaned_categories_file = (
    cleaned_path / "Product-Categories_Cleaned.csv"
)

categories.to_csv(
    cleaned_categories_file,
    index=False
)

print("Cleaned Product Categories file saved to:")
print(cleaned_categories_file.resolve())

Cleaned Product Categories file saved to:
C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned\Product-Categories_Cleaned.csv

In [ ]:
cleaned_categories = pd.read_csv(
    cleaned_path / "Product-Categories_Cleaned.csv"
)

print("Shape:", cleaned_categories.shape)

print("\nMissing ProductCategoryKey:",
      cleaned_categories["ProductCategoryKey"].isna().sum())

print("\nDuplicate ProductCategoryKeys:",
      cleaned_categories["ProductCategoryKey"].duplicated().sum())

print("\nCategories:")
print(cleaned_categories)

Shape: (4, 2)

Missing ProductCategoryKey: 0

Duplicate ProductCategoryKeys: 0

Categories:
   ProductCategoryKey CategoryName
0                   1        Bikes
1                   2   Components
2                   3     Clothing
3                   4  Accessories

In [ ]:
calendar = pd.read_csv(
    raw_path / "Calendar.csv"
)

print("Shape:", calendar.shape)

print("\nColumns:")
print(calendar.columns.tolist())

print("\nData types:")
print(calendar.dtypes)

print("\nFirst 5 rows:")
print(calendar.head())

Shape: (912, 1)

Columns:
['Date']

Data types:
Date    object
dtype: object

First 5 rows:
         Date
0  01-01-2015
1  02-01-2015
2  03-01-2015
3  04-01-2015
4  05-01-2015

In [ ]:
calendar["Date"] = pd.to_datetime(
    calendar["Date"],
    format="%d-%m-%Y"
)

print("Data type:", calendar["Date"].dtype)

print("\nFirst date:", calendar["Date"].min())
print("Last date:", calendar["Date"].max())

print("\nMissing dates:", calendar["Date"].isna().sum())
print("Duplicate dates:", calendar["Date"].duplicated().sum())

Data type: datetime64[ns]

First date: 2015-01-01 00:00:00
Last date: 2017-06-30 00:00:00

Missing dates: 0
Duplicate dates: 0

In [ ]:
expected_days = (
    calendar["Date"].max() - calendar["Date"].min()
).days + 1

actual_days = calendar["Date"].nunique()

print("Expected number of days:", expected_days)
print("Actual number of dates:", actual_days)
print("Missing calendar days:", expected_days - actual_days)

Expected number of days: 912
Actual number of dates: 912
Missing calendar days: 0

In [ ]:
cleaned_calendar_file = (
    cleaned_path / "Calendar_Cleaned.csv"
)

calendar.to_csv(
    cleaned_calendar_file,
    index=False
)

print("Cleaned Calendar file saved to:")
print(cleaned_calendar_file.resolve())

Cleaned Calendar file saved to:
C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned\Calendar_Cleaned.csv

In [ ]:
cleaned_calendar = pd.read_csv(
    cleaned_path / "Calendar_Cleaned.csv"
)

print("Shape:", cleaned_calendar.shape)

print("\nDate data type after loading CSV:",
      cleaned_calendar["Date"].dtype)

print("\nMissing dates:",
      cleaned_calendar["Date"].isna().sum())

print("\nDuplicate dates:",
      cleaned_calendar["Date"].duplicated().sum())

print("\nFirst 5 rows:")
print(cleaned_calendar.head())

Shape: (912, 1)

Date data type after loading CSV: object

Missing dates: 0

Duplicate dates: 0

First 5 rows:
         Date
0  2015-01-01
1  2015-01-02
2  2015-01-03
3  2015-01-04
4  2015-01-05

In [ ]:
territories = pd.read_csv(
    raw_path / "Territories.csv"
)

print("Shape:", territories.shape)

print("\nColumns:")
print(territories.columns.tolist())

print("\nData types:")
print(territories.dtypes)

print("\nFirst 5 rows:")
print(territories.head())

Shape: (10, 4)

Columns:
['SalesTerritoryKey', 'Region', 'Country', 'Continent']

Data types:
SalesTerritoryKey     int64
Region               object
Country              object
Continent            object
dtype: object

First 5 rows:
   SalesTerritoryKey     Region        Country      Continent
0                  1  Northwest  United States  North America
1                  2  Northeast  United States  North America
2                  3    Central  United States  North America
3                  4  Southwest  United States  North America
4                  5  Southeast  United States  North America

In [ ]:
print("Missing SalesTerritoryKey:",
      territories["SalesTerritoryKey"].isna().sum())

print("Unique SalesTerritoryKeys:",
      territories["SalesTerritoryKey"].nunique())

print("Duplicate SalesTerritoryKeys:",
      territories["SalesTerritoryKey"].duplicated().sum())

print("\nMissing values by column:")
print(territories.isna().sum())

print("\nDuplicate entire rows:",
      territories.duplicated().sum())

Missing SalesTerritoryKey: 0
Unique SalesTerritoryKeys: 10
Duplicate SalesTerritoryKeys: 0

Missing values by column:
SalesTerritoryKey    0
Region               0
Country              0
Continent            0
dtype: int64

Duplicate entire rows: 0

In [ ]:
print(
    territories.sort_values("SalesTerritoryKey").to_string(index=False)
)

 SalesTerritoryKey         Region        Country     Continent
                 1      Northwest  United States North America
                 2      Northeast  United States North America
                 3        Central  United States North America
                 4      Southwest  United States North America
                 5      Southeast  United States North America
                 6         Canada         Canada North America
                 7         France         France        Europe
                 8        Germany        Germany        Europe
                 9      Australia      Australia       Pacific
                10 United Kingdom United Kingdom        Europe

In [ ]:
cleaned_territories_file = (
    cleaned_path / "Territories_Cleaned.csv"
)

territories.to_csv(
    cleaned_territories_file,
    index=False
)

print("Cleaned Territories file saved to:")
print(cleaned_territories_file.resolve())

Cleaned Territories file saved to:
C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned\Territories_Cleaned.csv

In [ ]:
cleaned_territories = pd.read_csv(
    cleaned_path / "Territories_Cleaned.csv"
)

print("Shape:", cleaned_territories.shape)

print("\nMissing values:")
print(cleaned_territories.isna().sum())

print("\nDuplicate SalesTerritoryKeys:",
      cleaned_territories["SalesTerritoryKey"].duplicated().sum())

print("\nTerritories:")
print(cleaned_territories)

Shape: (10, 4)

Missing values:
SalesTerritoryKey    0
Region               0
Country              0
Continent            0
dtype: int64

Duplicate SalesTerritoryKeys: 0

Territories:
   SalesTerritoryKey          Region         Country      Continent
0                  1       Northwest   United States  North America
1                  2       Northeast   United States  North America
2                  3         Central   United States  North America
3                  4       Southwest   United States  North America
4                  5       Southeast   United States  North America
5                  6          Canada          Canada  North America
6                  7          France          France         Europe
7                  8         Germany         Germany         Europe
8                  9       Australia       Australia        Pacific
9                 10  United Kingdom  United Kingdom         Europe

In [ ]:
sales_2015 = pd.read_csv(
    raw_path / "Sales2015.csv"
)

print("Shape:", sales_2015.shape)

print("\nColumns:")
print(sales_2015.columns.tolist())

print("\nData types:")
print(sales_2015.dtypes)

print("\nFirst 5 rows:")
print(sales_2015.head())

Shape: (2630, 8)

Columns:
['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity']

Data types:
OrderDate        object
StockDate        object
OrderNumber      object
ProductKey        int64
CustomerKey       int64
TerritoryKey      int64
OrderLineItem     int64
OrderQuantity     int64
dtype: object

First 5 rows:
    OrderDate   StockDate OrderNumber  ProductKey  CustomerKey  TerritoryKey  \
0  2015-01-01  2001-09-21     SO45080         332        14657             1
1  2015-01-01  2001-05-12     SO45079         312        29255             4
2  2015-01-01  2001-10-29     SO45082         350        11455             9
3  2015-01-01  2001-11-16     SO45081         338        26782             6
4  2015-01-02  2001-12-15     SO45083         312        14947            10

   OrderLineItem  OrderQuantity
0              1              1
1              1              1
2              1              1
3              1              1
4              1              1

In [ ]:
print("OrderDate range:")
print("Minimum:", sales_2015["OrderDate"].min())
print("Maximum:", sales_2015["OrderDate"].max())

print("\nStockDate range:")
print("Minimum:", sales_2015["StockDate"].min())
print("Maximum:", sales_2015["StockDate"].max())

print("\nUnique OrderDates:",
      sales_2015["OrderDate"].nunique())

print("Unique StockDates:",
      sales_2015["StockDate"].nunique())

OrderDate range:
Minimum: 2015-01-01
Maximum: 2015-12-31

StockDate range:
Minimum: 2001-01-10
Maximum: 2002-12-14

Unique OrderDates: 365
Unique StockDates: 446

In [ ]:
sales_2015["OrderDate_dt"] = pd.to_datetime(
    sales_2015["OrderDate"],
    format="%Y-%m-%d"
)

sales_2015["StockDate_dt"] = pd.to_datetime(
    sales_2015["StockDate"],
    format="%Y-%m-%d"
)

sales_2015["Days_Order_to_Stock"] = (
    sales_2015["StockDate_dt"] - sales_2015["OrderDate_dt"]
).dt.days

print("Minimum difference:",
      sales_2015["Days_Order_to_Stock"].min())

print("Maximum difference:",
      sales_2015["Days_Order_to_Stock"].max())

print("\nNegative differences:",
      (sales_2015["Days_Order_to_Stock"] < 0).sum())

print("\nSample differences:")
print(
    sales_2015[
        ["OrderDate", "StockDate", "Days_Order_to_Stock"]
    ].head(10)
)

Minimum difference: -5159
Maximum difference: -4450

Negative differences: 2630

Sample differences:
    OrderDate   StockDate  Days_Order_to_Stock
0  2015-01-01  2001-09-21                -4850
1  2015-01-01  2001-05-12                -4982
2  2015-01-01  2001-10-29                -4812
3  2015-01-01  2001-11-16                -4794
4  2015-01-02  2001-12-15                -4766
5  2015-01-02  2001-12-10                -4771
6  2015-01-02  2001-12-18                -4763
7  2015-01-02  2001-09-10                -4862
8  2015-01-03  2001-03-10                -5047
9  2015-01-03  2001-09-29                -4844

In [ ]:
sales_2016 = pd.read_csv(
    raw_path / "Sales-2016.csv"
)

sales_2017 = pd.read_csv(
    raw_path / "Sales-2017.csv"
)

for year, df in [
    ("2015", sales_2015),
    ("2016", sales_2016),
    ("2017", sales_2017)
]:
    order_date = pd.to_datetime(df["OrderDate"])
    stock_date = pd.to_datetime(df["StockDate"])

    difference = (stock_date - order_date).dt.days

    print(f"\n--- {year} ---")
    print("Rows:", len(df))
    print("OrderDate range:",
          order_date.min().date(), "to", order_date.max().date())
    print("StockDate range:",
          stock_date.min().date(), "to", stock_date.max().date())
    print("Minimum difference:", difference.min())
    print("Maximum difference:", difference.max())
    print("StockDate after OrderDate:",
          (difference > 0).sum())

--- 2015 ---
Rows: 2630
OrderDate range: 2015-01-01 to 2015-12-31
StockDate range: 2001-01-10 to 2002-12-14
Minimum difference: -5159
Maximum difference: -4450
StockDate after OrderDate: 0

--- 2016 ---
Rows: 23935
OrderDate range: 2016-01-01 to 2016-12-31
StockDate range: 2002-09-06 to 2003-12-16
Minimum difference: -4869
Maximum difference: -4763
StockDate after OrderDate: 0

--- 2017 ---
Rows: 29481
OrderDate range: 2017-01-01 to 2017-06-30
StockDate range: 2003-09-03 to 2004-06-15
Minimum difference: -4869
Maximum difference: -4763
StockDate after OrderDate: 0

In [ ]:
print("Missing values in Sales 2015:")
print(sales_2015.isna().sum())

print("\nDuplicate entire rows:",
      sales_2015.duplicated().sum())

Missing values in Sales 2015:
OrderDate              0
StockDate              0
OrderNumber            0
ProductKey             0
CustomerKey            0
TerritoryKey           0
OrderLineItem          0
OrderQuantity          0
OrderDate_dt           0
StockDate_dt           0
Days_Order_to_Stock    0
dtype: int64

Duplicate entire rows: 0

In [ ]:
print("Minimum OrderQuantity:",
      sales_2015["OrderQuantity"].min())

print("Maximum OrderQuantity:",
      sales_2015["OrderQuantity"].max())

print("Zero quantities:",
      (sales_2015["OrderQuantity"] == 0).sum())

print("Negative quantities:",
      (sales_2015["OrderQuantity"] < 0).sum())

print("\nOrderQuantity distribution:")
print(
    sales_2015["OrderQuantity"]
    .value_counts()
    .sort_index()
)

Minimum OrderQuantity: 1
Maximum OrderQuantity: 1
Zero quantities: 0
Negative quantities: 0

OrderQuantity distribution:
OrderQuantity
1    2630
Name: count, dtype: int64

In [ ]:
valid_product_keys = set(products["ProductKey"])

invalid_product_keys = (
    ~sales_2015["ProductKey"].isin(valid_product_keys)
)

print("Unique ProductKeys in Sales 2015:",
      sales_2015["ProductKey"].nunique())

print("Invalid ProductKeys:",
      invalid_product_keys.sum())

print("\nInvalid ProductKey values:")
print(
    sales_2015.loc[
        invalid_product_keys,
        "ProductKey"
    ].unique()
)

Unique ProductKeys in Sales 2015: 44
Invalid ProductKeys: 0

Invalid ProductKey values:
[]

In [ ]:
valid_customer_keys = set(customers["CustomerKey"])

invalid_customer_keys = (
    ~sales_2015["CustomerKey"].isin(valid_customer_keys)
)

print("Unique CustomerKeys in Sales 2015:",
      sales_2015["CustomerKey"].nunique())

print("Invalid CustomerKeys:",
      invalid_customer_keys.sum())

print("\nInvalid CustomerKey values:")
print(
    sales_2015.loc[
        invalid_customer_keys,
        "CustomerKey"
    ].unique()
)

Unique CustomerKeys in Sales 2015: 2630
Invalid CustomerKeys: 0

Invalid CustomerKey values:
[]

In [ ]:
valid_territory_keys = set(
    territories["SalesTerritoryKey"]
)

invalid_territory_keys = (
    ~sales_2015["TerritoryKey"].isin(valid_territory_keys)
)

print("Unique TerritoryKeys in Sales 2015:",
      sales_2015["TerritoryKey"].nunique())

print("Invalid TerritoryKeys:",
      invalid_territory_keys.sum())

print("\nInvalid TerritoryKey values:")
print(
    sales_2015.loc[
        invalid_territory_keys,
        "TerritoryKey"
    ].unique()
)

Unique TerritoryKeys in Sales 2015: 8
Invalid TerritoryKeys: 0

Invalid TerritoryKey values:
[]

In [ ]:
print("Unique OrderNumbers:",
      sales_2015["OrderNumber"].nunique())

print("Total Sales Rows:",
      len(sales_2015))

print("\nOrderLineItem range:")
print("Minimum:", sales_2015["OrderLineItem"].min())
print("Maximum:", sales_2015["OrderLineItem"].max())

print("\nDuplicate OrderNumber + OrderLineItem combinations:",
      sales_2015.duplicated(
          subset=["OrderNumber", "OrderLineItem"]
      ).sum())

Unique OrderNumbers: 2630
Total Sales Rows: 2630

OrderLineItem range:
Minimum: 1
Maximum: 1

Duplicate OrderNumber + OrderLineItem combinations: 0

In [ ]:
print("Invalid OrderDates:",
      sales_2015["OrderDate_dt"].isna().sum())

print("Invalid StockDates:",
      sales_2015["StockDate_dt"].isna().sum())

print("\nOrderDate year distribution:")
print(sales_2015["OrderDate_dt"].dt.year.value_counts().sort_index())

Invalid OrderDates: 0
Invalid StockDates: 0

OrderDate year distribution:
OrderDate_dt
2015    2630
Name: count, dtype: int64

In [ ]:
calendar_dates = set(calendar["Date"])

invalid_calendar_dates = ~sales_2015["OrderDate_dt"].isin(calendar_dates)

print("OrderDates not found in Calendar:",
      invalid_calendar_dates.sum())

OrderDates not found in Calendar: 0

In [ ]:
product_keys = set(products["ProductKey"])

invalid_product_keys = ~sales_2015["ProductKey"].isin(product_keys)

print("ProductKeys not found in Products:",
      invalid_product_keys.sum())

ProductKeys not found in Products: 0

In [ ]:
customer_keys = set(customers["CustomerKey"])

invalid_customer_keys = ~sales_2015["CustomerKey"].isin(customer_keys)

print("CustomerKeys not found in Customers:",
      invalid_customer_keys.sum())

CustomerKeys not found in Customers: 0

In [ ]:
territory_keys = set(territories["SalesTerritoryKey"])

invalid_territory_keys = ~sales_2015["TerritoryKey"].isin(territory_keys)

print("TerritoryKeys not found in Territories:",
      invalid_territory_keys.sum())

TerritoryKeys not found in Territories: 0

In [ ]:
print("ProductKey <= 0:",
      (sales_2015["ProductKey"] <= 0).sum())

print("CustomerKey <= 0:",
      (sales_2015["CustomerKey"] <= 0).sum())

print("TerritoryKey <= 0:",
      (sales_2015["TerritoryKey"] <= 0).sum())

print("OrderLineItem <= 0:",
      (sales_2015["OrderLineItem"] <= 0).sum())

print("OrderQuantity <= 0:",
      (sales_2015["OrderQuantity"] <= 0).sum())

ProductKey <= 0: 0
CustomerKey <= 0: 0
TerritoryKey <= 0: 0
OrderLineItem <= 0: 0
OrderQuantity <= 0: 0

In [ ]:
print("OrderQuantity distribution:")
print(sales_2015["OrderQuantity"].value_counts().sort_index())

OrderQuantity distribution:
OrderQuantity
1    2630
Name: count, dtype: int64

In [ ]:
total_rows = len(sales_2015)
unique_orders = sales_2015["OrderNumber"].nunique()

print("Total Sales Rows:", total_rows)
print("Unique Orders:", unique_orders)
print("Rows per Order:", total_rows / unique_orders)

Total Sales Rows: 2630
Unique Orders: 2630
Rows per Order: 1.0

In [ ]:
duplicate_order_lines = sales_2015.duplicated(
    subset=["OrderNumber", "OrderLineItem"]
).sum()

print("Duplicate OrderNumber + OrderLineItem combinations:",
      duplicate_order_lines)

Duplicate OrderNumber + OrderLineItem combinations: 0

In [ ]:
territory_distribution = (
    sales_2015["TerritoryKey"]
    .value_counts()
    .sort_index()
)

print(territory_distribution)

TerritoryKey
1     334
4     514
5       1
6     223
7     229
8     226
9     848
10    255
Name: count, dtype: int64

In [ ]:
territory_sales = sales_2015.merge(
    territories,
    left_on="TerritoryKey",
    right_on="SalesTerritoryKey",
    how="left"
)

territory_summary = (
    territory_sales["Region"]
    .value_counts()
    .sort_index()
)

print(territory_summary)

Region
Australia         848
Canada            223
France            229
Germany           226
Northwest         334
Southeast           1
Southwest         514
United Kingdom    255
Name: count, dtype: int64

In [ ]:
product_distribution = (
    sales_2015["ProductKey"]
    .value_counts()
)

print("Unique Products Sold:", product_distribution.size)
print("\nTop 10 Products by Sales Transactions:")
print(product_distribution.head(10))

Unique Products Sold: 44

Top 10 Products by Sales Transactions:
ProductKey
312    179
310    169
313    168
314    157
311    139
377    108
371    106
369     90
375     83
370     80
Name: count, dtype: int64

In [ ]:
product_sales = sales_2015.merge(
    products[["ProductKey", "ProductName"]],
    on="ProductKey",
    how="left"
)

top_products = (
    product_sales
    .groupby(["ProductKey", "ProductName"])
    .size()
    .sort_values(ascending=False)
    .head(10)
)

print(top_products)

ProductKey  ProductName
312         Road-150 Red, 48      179
310         Road-150 Red, 62      169
313         Road-150 Red, 52      168
314         Road-150 Red, 56      157
311         Road-150 Red, 44      139
377         Road-250 Black, 52    108
371         Road-250 Red, 58      106
369         Road-250 Red, 48       90
375         Road-250 Black, 48     83
370         Road-250 Red, 52       80
dtype: int64

In [ ]:
product_category_sales = (
    sales_2015
    .merge(
        products[["ProductKey", "ProductSubcategoryKey"]],
        on="ProductKey",
        how="left"
    )
    .merge(
        subcategories[
            ["ProductSubcategoryKey", "ProductCategoryKey"]
        ],
        on="ProductSubcategoryKey",
        how="left"
    )
    .merge(
        categories,
        on="ProductCategoryKey",
        how="left"
    )
)

category_summary = (
    product_category_sales["CategoryName"]
    .value_counts()
)

print(category_summary)

CategoryName
Bikes    2630
Name: count, dtype: int64

In [ ]:
product_category_sales = (
    sales_2015
    .merge(
        products[["ProductKey", "ProductSubcategoryKey"]],
        on="ProductKey",
        how="left"
    )
    .merge(
        subcategories[
            ["ProductSubcategoryKey", "SubcategoryName", "ProductCategoryKey"]
        ],
        on="ProductSubcategoryKey",
        how="left"
    )
    .merge(
        categories,
        on="ProductCategoryKey",
        how="left"
    )
)

print(product_category_sales[
    ["ProductKey", "ProductSubcategoryKey", "SubcategoryName", "CategoryName"]
].head())

   ProductKey  ProductSubcategoryKey SubcategoryName CategoryName
0         332                      2      Road Bikes        Bikes
1         312                      2      Road Bikes        Bikes
2         350                      1  Mountain Bikes        Bikes
3         338                      2      Road Bikes        Bikes
4         312                      2      Road Bikes        Bikes

In [ ]:
subcategory_summary = (
    product_category_sales["SubcategoryName"]
    .value_counts()
)

print(subcategory_summary)

SubcategoryName
Road Bikes        2027
Mountain Bikes     603
Name: count, dtype: int64

In [ ]:
customer_distribution = (
    sales_2015["CustomerKey"]
    .value_counts()
)

print("Unique Customers:", customer_distribution.size)

print("\nTop 10 Customers by Transactions:")
print(customer_distribution.head(10))

Unique Customers: 2630

Top 10 Customers by Transactions:
CustomerKey
14657    1
29255    1
11455    1
26782    1
14947    1
29143    1
18747    1
18746    1
18906    1
29170    1
Name: count, dtype: int64

In [ ]:
print("Customers with more than 1 transaction:",
      (customer_distribution > 1).sum())

print("Maximum transactions by a customer:",
      customer_distribution.max())

Customers with more than 1 transaction: 0
Maximum transactions by a customer: 1

In [ ]:
monthly_sales_2015 = (
    sales_2015["OrderDate_dt"]
    .dt.month
    .value_counts()
    .sort_index()
)

print(monthly_sales_2015)

OrderDate_dt
1     184
2     165
3     198
4     204
5     206
6     212
7     247
8     278
9     196
10    223
11    191
12    326
Name: count, dtype: int64

In [ ]:
daily_sales_2015 = (
    sales_2015["OrderDate_dt"]
    .value_counts()
    .sort_index()
)

all_calendar_dates_2015 = calendar[
    calendar["Date"].dt.year == 2015
]["Date"]

zero_sales_days = (
    ~all_calendar_dates_2015.isin(daily_sales_2015.index)
).sum()

print("Days in Calendar:", len(all_calendar_dates_2015))
print("Days with Sales:", daily_sales_2015.size)
print("Days with Zero Sales:", zero_sales_days)

Days in Calendar: 365
Days with Sales: 365
Days with Zero Sales: 0

In [ ]:
print("Busiest Sales Day:")
print(daily_sales_2015.idxmax(), "→", daily_sales_2015.max(), "transactions")

print("\nSlowest Sales Day:")
print(daily_sales_2015.idxmin(), "→", daily_sales_2015.min(), "transaction(s)")

Busiest Sales Day:
2015-12-07 00:00:00 → 17 transactions

Slowest Sales Day:
2015-02-21 00:00:00 → 1 transaction(s)

In [ ]:
average_daily_transactions = daily_sales_2015.mean()

print("Average Transactions per Day:",
      round(average_daily_transactions, 2))

Average Transactions per Day: 7.21

In [ ]:
print("OrderNumber data type:", sales_2015["OrderNumber"].dtype)

print("\nFirst 10 OrderNumbers:")
print(sales_2015["OrderNumber"].head(10).to_list())

print("\nOrderNumber lengths:")
print(
    sales_2015["OrderNumber"]
    .str.len()
    .value_counts()
    .sort_index()
)

OrderNumber data type: object

First 10 OrderNumbers:
['SO45080', 'SO45079', 'SO45082', 'SO45081', 'SO45083', 'SO45084', 'SO45086', 'SO45085', 'SO45093', 'SO45090']

OrderNumber lengths:
OrderNumber
7    2630
Name: count, dtype: int64

In [ ]:
invalid_order_numbers = ~sales_2015["OrderNumber"].str.match(
    r"^SO\d{5}$"
)

print("Invalid OrderNumber formats:",
      invalid_order_numbers.sum())

Invalid OrderNumber formats: 0

In [ ]:
order_numbers = (
    sales_2015["OrderNumber"]
    .str.replace("SO", "", regex=False)
    .astype(int)
)

print("Minimum Order Number:", order_numbers.min())
print("Maximum Order Number:", order_numbers.max())
print("Unique Order Numbers:", order_numbers.nunique())

expected_order_count = (
    order_numbers.max() - order_numbers.min() + 1
)

print("Expected Sequential Count:", expected_order_count)
print("Missing Order Numbers:",
      expected_order_count - order_numbers.nunique())

Minimum Order Number: 45079
Maximum Order Number: 48729
Unique Order Numbers: 2630
Expected Sequential Count: 3651
Missing Order Numbers: 1021

In [ ]:
sales_2016 = pd.read_csv(raw_path / "Sales-2016.csv")
sales_2017 = pd.read_csv(raw_path / "Sales-2017.csv")

orders_2015 = set(sales_2015["OrderNumber"])
orders_2016 = set(sales_2016["OrderNumber"])
orders_2017 = set(sales_2017["OrderNumber"])

print("2015 ∩ 2016:", len(orders_2015 & orders_2016))
print("2015 ∩ 2017:", len(orders_2015 & orders_2017))
print("2016 ∩ 2017:", len(orders_2016 & orders_2017))

2015 ∩ 2016: 0
2015 ∩ 2017: 0
2016 ∩ 2017: 0

In [ ]:
invalid_stock_dates = pd.to_datetime(
    sales_2015["StockDate"],
    format="%Y-%m-%d",
    errors="coerce"
).isna()

print("Invalid StockDate values:",
      invalid_stock_dates.sum())

Invalid StockDate values: 0

In [ ]:
print("Missing StockDate values:",
      sales_2015["StockDate"].isna().sum())

print("Missing OrderDate values:",
      sales_2015["OrderDate"].isna().sum())

Missing StockDate values: 0
Missing OrderDate values: 0

In [ ]:
print("Unique StockDates:",
      sales_2015["StockDate"].nunique())

print("StockDate range:")
print("Minimum:", sales_2015["StockDate"].min())
print("Maximum:", sales_2015["StockDate"].max())

Unique StockDates: 446
StockDate range:
Minimum: 2001-01-10
Maximum: 2002-12-14

In [ ]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    print(f"\n{year}")
    print("Minimum:", df["OrderQuantity"].min())
    print("Maximum:", df["OrderQuantity"].max())
    print("Unique quantities:", df["OrderQuantity"].nunique())
    print("Quantity distribution:")
    print(df["OrderQuantity"].value_counts().sort_index())

2015
Minimum: 1
Maximum: 1
Unique quantities: 1
Quantity distribution:
OrderQuantity
1    2630
Name: count, dtype: int64

2016
Minimum: 1
Maximum: 3
Unique quantities: 3
Quantity distribution:
OrderQuantity
1    13192
2     9191
3     1552
Name: count, dtype: int64

2017
Minimum: 1
Maximum: 3
Unique quantities: 3
Quantity distribution:
OrderQuantity
1    15599
2    11931
3     1951
Name: count, dtype: int64

In [ ]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    total_units = df["OrderQuantity"].sum()

    print(f"{year} Total Units Sold:", total_units)

2015 Total Units Sold: 2630
2016 Total Units Sold: 36230
2017 Total Units Sold: 45314

In [ ]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    average_quantity = df["OrderQuantity"].mean()

    print(
        f"{year} Average Units per Sales Line:",
        round(average_quantity, 2)
    )

2015 Average Units per Sales Line: 1.0
2016 Average Units per Sales Line: 1.51
2017 Average Units per Sales Line: 1.54

In [ ]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    print(f"\n{year}")
    print("Minimum:", df["OrderLineItem"].min())
    print("Maximum:", df["OrderLineItem"].max())
    print("Unique values:", df["OrderLineItem"].nunique())
    print("Distribution:")
    print(df["OrderLineItem"].value_counts().sort_index())

2015
Minimum: 1
Maximum: 1
Unique values: 1
Distribution:
OrderLineItem
1    2630
Name: count, dtype: int64

2016
Minimum: 1
Maximum: 8
Unique values: 8
Distribution:
OrderLineItem
1    10695
2     7293
3     3993
4     1576
5      320
6       51
7        6
8        1
Name: count, dtype: int64

2017
Minimum: 1
Maximum: 8
Unique values: 8
Distribution:
OrderLineItem
1    11839
2     9626
3     5272
4     2201
5      467
6       66
7        8
8        2
Name: count, dtype: int64

In [ ]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    unique_orders = df["OrderNumber"].nunique()

    print(f"{year} Unique Orders:", unique_orders)

2015 Unique Orders: 2630
2016 Unique Orders: 10695
2017 Unique Orders: 11839

In [ ]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    lines_per_order = (
        df.groupby("OrderNumber")
        .size()
        .mean()
    )

    print(
        f"{year} Average Sales Lines per Order:",
        round(lines_per_order, 2)
    )

NameError: name 'sales_2015' is not defined

In [22]:

for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    lines_per_order = df.groupby("OrderNumber").size()

    print(f"\n{year}")
    print("Maximum lines in a single order:",
          lines_per_order.max())

    print("Orders with maximum lines:",
          (lines_per_order == lines_per_order.max()).sum())

NameError: name 'sales_2015' is not defined

In [23]:
from pathlib import Path
import pandas as pd

raw_path = Path("../data/raw")

sales_2015 = pd.read_csv(raw_path / "Sales2015.csv")
sales_2016 = pd.read_csv(raw_path / "Sales-2016.csv")
sales_2017 = pd.read_csv(raw_path / "Sales-2017.csv")

print("2015:", sales_2015.shape)
print("2016:", sales_2016.shape)
print("2017:", sales_2017.shape)

2015: (2630, 8)
2016: (23935, 8)
2017: (29481, 8)

In [24]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    lines_per_order = df.groupby("OrderNumber").size()

    print(f"\n{year}")
    print("Maximum lines in a single order:",
          lines_per_order.max())

    print("Orders with maximum lines:",
          (lines_per_order == lines_per_order.max()).sum())

2015
Maximum lines in a single order: 1
Orders with maximum lines: 2630

2016
Maximum lines in a single order: 8
Orders with maximum lines: 1

2017
Maximum lines in a single order: 8
Orders with maximum lines: 2

In [25]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    sequence_issues = 0

    for order_number, group in df.groupby("OrderNumber"):
        line_items = sorted(group["OrderLineItem"].tolist())
        expected = list(range(1, len(line_items) + 1))

        if line_items != expected:
            sequence_issues += 1

    print(f"{year} Orders with LineItem Sequence Issues:",
          sequence_issues)

2015 Orders with LineItem Sequence Issues: 0
2016 Orders with LineItem Sequence Issues: 0
2017 Orders with LineItem Sequence Issues: 0

In [26]:
customers_2015 = set(sales_2015["CustomerKey"])
customers_2016 = set(sales_2016["CustomerKey"])
customers_2017 = set(sales_2017["CustomerKey"])

print("Customers in 2015:", len(customers_2015))
print("Customers in 2016:", len(customers_2016))
print("Customers in 2017:", len(customers_2017))

print("\n2015 & 2016:", len(customers_2015 & customers_2016))
print("2015 & 2017:", len(customers_2015 & customers_2017))
print("2016 & 2017:", len(customers_2016 & customers_2017))

print(
    "All 3 years:",
    len(customers_2015 & customers_2016 & customers_2017)
)

Customers in 2015: 2630
Customers in 2016: 9133
Customers in 2017: 10502

2015 & 2016: 1204
2015 & 2017: 1546
2016 & 2017: 2397
All 3 years: 298

In [27]:
repeat_2016 = customers_2016 & customers_2015
repeat_2017 = customers_2017 & (customers_2015 | customers_2016)

print("Repeat customers in 2016:", len(repeat_2016))
print("Repeat customers in 2017:", len(repeat_2017))

Repeat customers in 2016: 1204
Repeat customers in 2017: 3645

In [28]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    orders_per_customer = (
        df.groupby("CustomerKey")["OrderNumber"]
        .nunique()
    )

    repeat_customers = (orders_per_customer > 1).sum()

    print(
        f"{year} Customers with Multiple Orders:",
        repeat_customers
    )

2015 Customers with Multiple Orders: 0
2016 Customers with Multiple Orders: 1209
2017 Customers with Multiple Orders: 947

In [29]:
for year, df in [
    (2015, sales_2015),
    (2016, sales_2016),
    (2017, sales_2017)
]:
    orders_per_customer = (
        df.groupby("CustomerKey")["OrderNumber"]
        .nunique()
    )

    average_orders = orders_per_customer.mean()

    print(
        f"{year} Average Orders per Customer:",
        round(average_orders, 2)
    )

2015 Average Orders per Customer: 1.0
2016 Average Orders per Customer: 1.17
2017 Average Orders per Customer: 1.13

In [30]:
sales_all = pd.concat(
    [sales_2015, sales_2016, sales_2017],
    ignore_index=True
)

print("Combined Sales Shape:", sales_all.shape)

print("\nCombined Sales Columns:")
print(sales_all.columns.tolist())

Combined Sales Shape: (56046, 8)

Combined Sales Columns:
['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity']

In [31]:
print("Missing values:")
print(sales_all.isnull().sum())

print("\nDuplicate rows:")
print(sales_all.duplicated().sum())

print("\nDate range:")
print("OrderDate:", sales_all["OrderDate"].min(), "to", sales_all["OrderDate"].max())
print("StockDate:", sales_all["StockDate"].min(), "to", sales_all["StockDate"].max())

print("\nUnique Orders:")
print(sales_all["OrderNumber"].nunique())

print("\nUnique Customers:")
print(sales_all["CustomerKey"].nunique())

print("\nUnique Products:")
print(sales_all["ProductKey"].nunique())

print("\nUnique Territories:")
print(sales_all["TerritoryKey"].nunique())

Missing values:
OrderDate        0
StockDate        0
OrderNumber      0
ProductKey       0
CustomerKey      0
TerritoryKey     0
OrderLineItem    0
OrderQuantity    0
dtype: int64

Duplicate rows:
0

Date range:
OrderDate: 2015-01-01 to 2017-06-30
StockDate: 2001-01-10 to 2004-06-15

Unique Orders:
25164

Unique Customers:
17416

Unique Products:
130

Unique Territories:
10

In [32]:
sales_all["OrderDate"] = pd.to_datetime(
    sales_all["OrderDate"],
    format="%Y-%m-%d"
)

sales_all["Year"] = sales_all["OrderDate"].dt.year

print(sales_all[["OrderDate", "Year"]].head())

print("\nYear distribution:")
print(sales_all["Year"].value_counts().sort_index())

   OrderDate  Year
0 2015-01-01  2015
1 2015-01-01  2015
2 2015-01-01  2015
3 2015-01-01  2015
4 2015-01-02  2015

Year distribution:
Year
2015     2630
2016    23935
2017    29481
Name: count, dtype: int64

In [33]:
combined_sales_file = cleaned_path / "Sales_All_Cleaned.csv"

sales_all.to_csv(
    combined_sales_file,
    index=False
)

print(f"Saved to: {combined_sales_file}")

NameError: name 'cleaned_path' is not defined

In [34]:
from pathlib import Path

cleaned_path = Path("../data/cleaned")

cleaned_path.mkdir(exist_ok=True)

print("Cleaned path:", cleaned_path.resolve())

Cleaned path: C:\Users\tejas\OneDrive\Desktop\AdventureWorks-Analytics\data\cleaned

In [35]:
combined_sales_file = cleaned_path / "Sales_All_Cleaned.csv"

sales_all.to_csv(
    combined_sales_file,
    index=False
)

print(f"Saved to: {combined_sales_file}")

Saved to: ..\data\cleaned\Sales_All_Cleaned.csv

In [36]:
sales_all_check = pd.read_csv(combined_sales_file)

print("Shape:", sales_all_check.shape)
print("Columns:", sales_all_check.columns.tolist())

Shape: (56046, 9)
Columns: ['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity', 'Year']

In [37]:
sales_by_year = (
    sales_all.groupby("Year")
    .agg(
        Transactions=("OrderNumber", "count"),
        Orders=("OrderNumber", "nunique"),
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

print(sales_by_year)

   Year  Transactions  Orders  Units_Sold
0  2015          2630    2630        2630
1  2016         23935   10695       36230
2  2017         29481   11839       45314

In [38]:
sales_by_year["Transactions_Growth_%"] = (
    sales_by_year["Transactions"]
    .pct_change()
    .mul(100)
    .round(2)
)

sales_by_year["Orders_Growth_%"] = (
    sales_by_year["Orders"]
    .pct_change()
    .mul(100)
    .round(2)
)

sales_by_year["Units_Growth_%"] = (
    sales_by_year["Units_Sold"]
    .pct_change()
    .mul(100)
    .round(2)
)

print(sales_by_year)

   Year  Transactions  Orders  Units_Sold  Transactions_Growth_%  \
0  2015          2630    2630        2630                    NaN
1  2016         23935   10695       36230                 810.08
2  2017         29481   11839       45314                  23.17

   Orders_Growth_%  Units_Growth_%
0              NaN             NaN
1           306.65         1277.57
2            10.70           25.07

In [39]:
sales_by_year["Lines_per_Order"] = (
    sales_by_year["Transactions"] /
    sales_by_year["Orders"]
).round(2)

sales_by_year["Units_per_Order"] = (
    sales_by_year["Units_Sold"] /
    sales_by_year["Orders"]
).round(2)

print(
    sales_by_year[
        ["Year", "Orders", "Transactions", "Units_Sold",
         "Lines_per_Order", "Units_per_Order"]
    ]
)

   Year  Orders  Transactions  Units_Sold  Lines_per_Order  Units_per_Order
0  2015    2630          2630        2630             1.00             1.00
1  2016   10695         23935       36230             2.24             3.39
2  2017   11839         29481       45314             2.49             3.83

In [40]:
products_clean = pd.read_csv(
    cleaned_path / "Products_Cleaned.csv"
)

print("Products shape:", products_clean.shape)
print(products_clean.columns.tolist())

Products shape: (293, 11)
['ProductKey', 'ProductSubcategoryKey', 'ProductSKU', 'ProductName', 'ModelName', 'ProductDescription', 'ProductColor', 'ProductSize', 'ProductStyle', 'ProductCost', 'ProductPrice']

In [41]:
sales_product = sales_all.merge(
    products_clean[
        ["ProductKey", "ProductName", "ProductSubcategoryKey",
         "ProductCost", "ProductPrice"]
    ],
    on="ProductKey",
    how="left"
)

print("Merged shape:", sales_product.shape)

print("\nMissing product information:")
print(
    sales_product[
        ["ProductName", "ProductCost", "ProductPrice"]
    ].isnull().sum()
)

Merged shape: (56046, 13)

Missing product information:
ProductName     0
ProductCost     0
ProductPrice    0
dtype: int64

In [42]:
sales_product["Revenue"] = (
    sales_product["OrderQuantity"] *
    sales_product["ProductPrice"]
)

sales_product["Cost"] = (
    sales_product["OrderQuantity"] *
    sales_product["ProductCost"]
)

sales_product["GrossProfit"] = (
    sales_product["Revenue"] -
    sales_product["Cost"]
)

sales_product["ProfitMargin_%"] = (
    sales_product["GrossProfit"] /
    sales_product["Revenue"] *
    100
).round(2)

print(
    sales_product[
        ["OrderQuantity", "ProductPrice", "ProductCost",
         "Revenue", "Cost", "GrossProfit", "ProfitMargin_%"]
    ].head(10)
)

   OrderQuantity  ProductPrice  ProductCost    Revenue       Cost  \
0              1      699.0982     413.1463   699.0982   413.1463
1              1     3578.2700    2171.2942  3578.2700  2171.2942
2              1     3374.9900    1898.0944  3374.9900  1898.0944
3              1      699.0982     413.1463   699.0982   413.1463
4              1     3578.2700    2171.2942  3578.2700  2171.2942
5              1     3578.2700    2171.2942  3578.2700  2171.2942
6              1     3578.2700    2171.2942  3578.2700  2171.2942
7              1     3578.2700    2171.2942  3578.2700  2171.2942
8              1     3578.2700    2171.2942  3578.2700  2171.2942
9              1     3578.2700    2171.2942  3578.2700  2171.2942

   GrossProfit  ProfitMargin_%
0     285.9519           40.90
1    1406.9758           39.32
2    1476.8956           43.76
3     285.9519           40.90
4    1406.9758           39.32
5    1406.9758           39.32
6    1406.9758           39.32
7    1406.9758           39.32
8    1406.9758           39.32
9    1406.9758           39.32

In [43]:
print("Revenue <= 0:", (sales_product["Revenue"] <= 0).sum())

print("Cost < 0:", (sales_product["Cost"] < 0).sum())

print("Gross Profit < 0:", (sales_product["GrossProfit"] < 0).sum())

print("Missing financial values:")
print(
    sales_product[
        ["Revenue", "Cost", "GrossProfit", "ProfitMargin_%"]
    ].isnull().sum()
)

print("\nProfit Margin range:")
print(
    sales_product["ProfitMargin_%"].min(),
    "to",
    sales_product["ProfitMargin_%"].max()
)

Revenue <= 0: 0
Cost < 0: 0
Gross Profit < 0: 0
Missing financial values:
Revenue           0
Cost              0
GrossProfit       0
ProfitMargin_%    0
dtype: int64

Profit Margin range:
23.0 to 64.25

In [1]:
annual_financials = (
    sales_product.groupby("Year")
    .agg(
        Revenue=("Revenue", "sum"),
        Cost=("Cost", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderNumber", "nunique"),
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

annual_financials["ProfitMargin_%"] = (
    annual_financials["GrossProfit"] /
    annual_financials["Revenue"] *
    100
).round(2)

annual_financials["Revenue_Growth_%"] = (
    annual_financials["Revenue"]
    .pct_change()
    .mul(100)
    .round(2)
)

annual_financials["Profit_Growth_%"] = (
    annual_financials["GrossProfit"]
    .pct_change()
    .mul(100)
    .round(2)
)

print(annual_financials)

NameError: name 'sales_product' is not defined

In [2]:
from pathlib import Path
import pandas as pd

# Set the cleaned data path
cleaned_path = Path("../data/cleaned")

# Reload the combined sales data
sales_all = pd.read_csv(
    cleaned_path / "Sales_All_Cleaned.csv"
)

# Convert OrderDate back to datetime
sales_all["OrderDate"] = pd.to_datetime(
    sales_all["OrderDate"],
    format="%Y-%m-%d"
)

# Reload the cleaned product data
products_clean = pd.read_csv(
    cleaned_path / "Products_Cleaned.csv"
)

# Merge sales with product information
sales_product = sales_all.merge(
    products_clean[
        ["ProductKey", "ProductName", "ProductSubcategoryKey",
         "ProductCost", "ProductPrice"]
    ],
    on="ProductKey",
    how="left"
)

# Recreate financial metrics
sales_product["Revenue"] = (
    sales_product["OrderQuantity"] *
    sales_product["ProductPrice"]
)

sales_product["Cost"] = (
    sales_product["OrderQuantity"] *
    sales_product["ProductCost"]
)

sales_product["GrossProfit"] = (
    sales_product["Revenue"] -
    sales_product["Cost"]
)

print("Sales shape:", sales_all.shape)
print("Sales + Product shape:", sales_product.shape)

Sales shape: (56046, 9)
Sales + Product shape: (56046, 16)

In [3]:
print(sales_product.columns.tolist())

['OrderDate', 'StockDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity', 'Year', 'ProductName', 'ProductSubcategoryKey', 'ProductCost', 'ProductPrice', 'Revenue', 'Cost', 'GrossProfit']

In [4]:
annual_financials = (
    sales_product.groupby("Year")
    .agg(
        Revenue=("Revenue", "sum"),
        Cost=("Cost", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderNumber", "nunique"),
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

annual_financials["ProfitMargin_%"] = (
    annual_financials["GrossProfit"] /
    annual_financials["Revenue"] *
    100
).round(2)

annual_financials["Revenue_Growth_%"] = (
    annual_financials["Revenue"]
    .pct_change()
    .mul(100)
    .round(2)
)

annual_financials["Profit_Growth_%"] = (
    annual_financials["GrossProfit"]
    .pct_change()
    .mul(100)
    .round(2)
)

print(annual_financials)

   Year       Revenue          Cost   GrossProfit  Orders  Units_Sold  \
0  2015  6.404934e+06  3.803331e+06  2.601602e+06    2630        2630
1  2016  9.324204e+06  5.357120e+06  3.967084e+06   10695       36230
2  2017  9.185449e+06  5.296420e+06  3.889029e+06   11839       45314

   ProfitMargin_%  Revenue_Growth_%  Profit_Growth_%
0           40.62               NaN              NaN
1           42.55             45.58            52.49
2           42.34             -1.49            -1.97

In [5]:
sales_product["Month"] = sales_product["OrderDate"].dt.month

monthly_revenue = (
    sales_product.groupby(["Year", "Month"])
    .agg(
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderNumber", "nunique")
    )
    .reset_index()
)

print(monthly_revenue)

    Year  Month       Revenue  GrossProfit  Orders
0   2015      1  5.853126e+05  235814.0303     184
1   2015      2  5.322262e+05  212186.6893     165
2   2015      3  6.434361e+05  259084.5226     198
3   2015      4  6.533640e+05  263031.3418     204
4   2015      5  6.593259e+05  266275.7522     206
5   2015      6  6.699887e+05  270067.5120     212
6   2015      7  4.861150e+05  196682.7944     247
7   2015      8  5.364528e+05  218355.4683     278
8   2015      9  3.440629e+05  140516.1465     196
9   2015     10  4.042766e+05  168581.7648     223
10  2015     11  3.266112e+05  134175.9813     191
11  2015     12  5.637615e+05  236830.3289     326
12  2016      1  4.324257e+05  182044.3796     242
13  2016      2  4.741628e+05  200044.3727     267
14  2016      3  4.719619e+05  199611.0413     266
15  2016      4  4.949574e+05  209521.6975     290
16  2016      5  5.455347e+05  233013.0757     329
17  2016      6  5.338250e+05  227745.0372     312
18  2016      7  8.153565e+05  342624.1294     506
19  2016      8  8.041934e+05  348095.7204    1543
20  2016      9  9.527435e+05  410592.0507    1568
21  2016     10  1.029821e+06  441168.0257    1639
22  2016     11  1.133913e+06  482940.3662    1677
23  2016     12  1.635309e+06  689684.2306    2056
24  2017      1  1.274379e+06  541843.7780    1811
25  2017      2  1.339241e+06  567573.8896    1758
26  2017      3  1.448596e+06  613453.1214    1962
27  2017      4  1.527814e+06  643826.5589    1997
28  2017      5  1.768433e+06  750754.3352    2165
29  2017      6  1.826987e+06  771577.2917    2146

In [6]:
h1_comparison = (
    monthly_revenue[
        monthly_revenue["Month"] <= 6
    ]
    .groupby("Year")
    .agg(
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("Orders", "sum")
    )
    .reset_index()
)

h1_comparison["Revenue_Growth_%"] = (
    h1_comparison["Revenue"]
    .pct_change()
    .mul(100)
    .round(2)
)

h1_comparison["Profit_Growth_%"] = (
    h1_comparison["GrossProfit"]
    .pct_change()
    .mul(100)
    .round(2)
)

print(h1_comparison)

   Year       Revenue   GrossProfit  Orders  Revenue_Growth_%  Profit_Growth_%
0  2015  3.743654e+06  1.506460e+06    1169               NaN              NaN
1  2016  2.952868e+06  1.251980e+06    1706            -21.12           -16.89
2  2017  9.185449e+06  3.889029e+06   11839            211.07           210.63

In [7]:
print(
    monthly_revenue[
        monthly_revenue["Year"] == 2017
    ]
)

    Year  Month       Revenue  GrossProfit  Orders
24  2017      1  1.274379e+06  541843.7780    1811
25  2017      2  1.339241e+06  567573.8896    1758
26  2017      3  1.448596e+06  613453.1214    1962
27  2017      4  1.527814e+06  643826.5589    1997
28  2017      5  1.768433e+06  750754.3352    2165
29  2017      6  1.826987e+06  771577.2917    2146

In [8]:
h1_comparison = (
    monthly_revenue[
        monthly_revenue["Month"].between(1, 6)
    ]
    .groupby("Year")
    .agg(
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("Orders", "sum")
    )
    .reset_index()
)

h1_comparison["Revenue_Growth_%"] = (
    h1_comparison["Revenue"]
    .pct_change()
    .mul(100)
    .round(2)
)

h1_comparison["Profit_Growth_%"] = (
    h1_comparison["GrossProfit"]
    .pct_change()
    .mul(100)
    .round(2)
)

print(h1_comparison)

   Year       Revenue   GrossProfit  Orders  Revenue_Growth_%  Profit_Growth_%
0  2015  3.743654e+06  1.506460e+06    1169               NaN              NaN
1  2016  2.952868e+06  1.251980e+06    1706            -21.12           -16.89
2  2017  9.185449e+06  3.889029e+06   11839            211.07           210.63

In [9]:
monthly_revenue_ranked = (
    monthly_revenue
    .sort_values("Revenue", ascending=False)
    .reset_index(drop=True)
)

print(
    monthly_revenue_ranked[
        ["Year", "Month", "Revenue", "GrossProfit", "Orders"]
    ].head(10)
)

   Year  Month       Revenue  GrossProfit  Orders
0  2017      6  1.826987e+06  771577.2917    2146
1  2017      5  1.768433e+06  750754.3352    2165
2  2016     12  1.635309e+06  689684.2306    2056
3  2017      4  1.527814e+06  643826.5589    1997
4  2017      3  1.448596e+06  613453.1214    1962
5  2017      2  1.339241e+06  567573.8896    1758
6  2017      1  1.274379e+06  541843.7780    1811
7  2016     11  1.133913e+06  482940.3662    1677
8  2016     10  1.029821e+06  441168.0257    1639
9  2016      9  9.527435e+05  410592.0507    1568

In [10]:
subcategories_clean = pd.read_csv(
    cleaned_path / "Product-Subcategories_Cleaned.csv"
)

categories_clean = pd.read_csv(
    cleaned_path / "Product-Categories_Cleaned.csv"
)

sales_category = sales_product.merge(
    subcategories_clean[
        ["ProductSubcategoryKey", "SubcategoryName",
         "ProductCategoryKey"]
    ],
    on="ProductSubcategoryKey",
    how="left"
)

sales_category = sales_category.merge(
    categories_clean[
        ["ProductCategoryKey", "CategoryName"]
    ],
    on="ProductCategoryKey",
    how="left"
)

print("Shape:", sales_category.shape)

print("\nMissing category information:")
print(
    sales_category[
        ["SubcategoryName", "CategoryName"]
    ].isnull().sum()
)

Shape: (56046, 20)

Missing category information:
SubcategoryName    0
CategoryName       0
dtype: int64

In [11]:
print("Unique subcategories in sales:", sales_category["ProductSubcategoryKey"].nunique())
print("Unique categories in sales:", sales_category["ProductCategoryKey"].nunique())

print("\nCategory distribution:")
print(
    sales_category["CategoryName"]
    .value_counts()
)

print("\nSubcategory distribution:")
print(
    sales_category["SubcategoryName"]
    .value_counts().head(10)
)

Unique subcategories in sales: 17
Unique categories in sales: 3

Category distribution:
CategoryName
Accessories    33607
Bikes          13929
Clothing        8510
Name: count, dtype: int64

Subcategory distribution:
SubcategoryName
Tires and Tubes      15970
Bottles and Cages     7547
Road Bikes            7099
Helmets               6034
Mountain Bikes        4706
Jerseys               3113
Touring Bikes         2124
Caps                  2062
Fenders               1975
Gloves                1332
Name: count, dtype: int64

In [12]:
category_performance = (
    sales_category
    .groupby("CategoryName")
    .agg(
        Revenue=("Revenue", "sum"),
        Cost=("Cost", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Units_Sold=("OrderQuantity", "sum"),
        Orders=("OrderNumber", "nunique")
    )
    .reset_index()
)

category_performance["ProfitMargin_%"] = (
    category_performance["GrossProfit"]
    / category_performance["Revenue"]
    * 100
).round(2)

category_performance = category_performance.sort_values(
    "Revenue",
    ascending=False
)

category_performance

,CategoryName,Revenue,Cost,GrossProfit,Units_Sold,Orders,ProfitMargin_%
1,Bikes,2.364250e+07,1.391633e+07,9.726168e+06,13929,13929,41.14
0,Accessories,9.066731e+05,3.369130e+05,5.697601e+05,57809,16983,62.84
2,Clothing,3.654186e+05,2.036315e+05,1.617871e+05,12436,6976,44.27

In [13]:
subcategory_performance = (
    sales_category
    .groupby("SubcategoryName")
    .agg(
        Revenue=("Revenue", "sum"),
        Cost=("Cost", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Units_Sold=("OrderQuantity", "sum"),
        Orders=("OrderNumber", "nunique")
    )
    .reset_index()
)

subcategory_performance["ProfitMargin_%"] = (
    subcategory_performance["GrossProfit"]
    / subcategory_performance["Revenue"]
    * 100
).round(2)

subcategory_performance = subcategory_performance.sort_values(
    "Revenue",
    ascending=False
)

subcategory_performance

,SubcategoryName,Revenue,Cost,GrossProfit,Units_Sold,Orders,ProfitMargin_%
11,Road Bikes,1.128718e+07,6.918836e+06,4.368347e+06,7099,7099,38.70
10,Mountain Bikes,8.583748e+06,4.653086e+06,3.930662e+06,4706,4706,45.79
15,Touring Bikes,3.771565e+06,2.344405e+06,1.427160e+06,2124,2124,37.84
14,Tires and Tubes,3.808267e+05,1.424303e+05,2.383964e+05,29772,9084,62.60
7,Helmets,2.058339e+05,7.479754e+04,1.310364e+05,6034,6034,63.66
9,Jerseys,1.585649e+05,1.136087e+05,4.495625e+04,3113,3113,28.35
2,Bottles and Cages,1.077449e+05,4.029721e+04,6.744773e+04,15106,4485,62.60
5,Fenders,8.704080e+04,3.255318e+04,5.448762e+04,3960,1975,62.60
12,Shorts,6.607056e+04,2.471043e+04,4.136013e+04,944,944,62.60
6,Gloves,6.226118e+04,2.568276e+04,3.657842e+04,2644,1332,58.75
8,Hydration Packs,3.821805e+04,1.429358e+04,2.392447e+04,695,695,62.60
1,Bike Stands,3.720600e+04,1.391504e+04,2.329096e+04,234,234,62.60
0,Bike Racks,3.624000e+04,1.355376e+04,2.268624e+04,302,302,62.60
3,Caps,3.588207e+04,2.368229e+04,1.219979e+04,4151,2062,34.00
16,Vests,3.308350e+04,1.237323e+04,2.071027e+04,521,521,62.60
4,Cleaners,1.356270e+04,5.072450e+03,8.490250e+03,1706,850,62.60
13,Socks,9.556370e+03,3.574125e+03,5.982245e+03,1063,538,62.60

In [14]:
product_performance = (
    sales_category
    .groupby(["ProductKey", "ProductName"])
    .agg(
        Revenue=("Revenue", "sum"),
        Cost=("Cost", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Units_Sold=("OrderQuantity", "sum"),
        Orders=("OrderNumber", "nunique")
    )
    .reset_index()
)

product_performance["ProfitMargin_%"] = (
    product_performance["GrossProfit"]
    / product_performance["Revenue"]
    * 100
).round(2)

product_performance = product_performance.sort_values(
    "Revenue",
    ascending=False
)

product_performance.head(10)

,ProductKey,ProductName,Revenue,Cost,GrossProfit,Units_Sold,Orders,ProfitMargin_%
38,362,"Mountain-200 Black, 46",1.241754e+06,670120.8600,571632.6492,606,606,46.03
37,360,"Mountain-200 Black, 42",1.233557e+06,665697.6200,567859.4964,602,602,46.03
33,352,"Mountain-200 Silver, 38",1.213852e+06,655063.5574,558788.3282,586,586,46.03
35,356,"Mountain-200 Silver, 46",1.182781e+06,638295.7189,544484.8727,571,571,46.03
36,358,"Mountain-200 Black, 38",1.165937e+06,629205.8900,536730.9858,569,569,46.03
34,354,"Mountain-200 Silver, 42",1.133067e+06,611467.1773,521599.3439,547,547,46.03
45,377,"Road-250 Black, 52",6.893738e+05,417336.0808,272037.6692,316,316,39.46
42,371,"Road-250 Red, 58",6.610134e+05,400167.1914,260846.2461,303,303,39.46
44,375,"Road-250 Black, 48",6.413794e+05,388281.0372,253098.3378,294,294,39.46
10,312,"Road-150 Red, 48",6.405103e+05,388661.6618,251848.6682,179,179,39.32

In [15]:
top_profit_products = (
    product_performance
    .sort_values("GrossProfit", ascending=False)
    .head(10)
)

top_profit_products[
    [
        "ProductKey",
        "ProductName",
        "Revenue",
        "GrossProfit",
        "Units_Sold",
        "Orders",
        "ProfitMargin_%"
    ]
]

,ProductKey,ProductName,Revenue,GrossProfit,Units_Sold,Orders,ProfitMargin_%
38,362,"Mountain-200 Black, 46",1.241754e+06,571632.6492,606,606,46.03
37,360,"Mountain-200 Black, 42",1.233557e+06,567859.4964,602,602,46.03
33,352,"Mountain-200 Silver, 38",1.213852e+06,558788.3282,586,586,46.03
35,356,"Mountain-200 Silver, 46",1.182781e+06,544484.8727,571,571,46.03
36,358,"Mountain-200 Black, 38",1.165937e+06,536730.9858,569,569,46.03
34,354,"Mountain-200 Silver, 42",1.133067e+06,521599.3439,547,547,46.03
45,377,"Road-250 Black, 52",6.893738e+05,272037.6692,316,316,39.46
42,371,"Road-250 Red, 58",6.610134e+05,260846.2461,303,303,39.46
44,375,"Road-250 Black, 48",6.413794e+05,253098.3378,294,294,39.46
10,312,"Road-150 Red, 48",6.405103e+05,251848.6682,179,179,39.32

In [16]:
customer_performance = (
    sales_category
    .groupby("CustomerKey")
    .agg(
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderNumber", "nunique"),
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

customer_performance["ProfitMargin_%"] = (
    customer_performance["GrossProfit"]
    / customer_performance["Revenue"]
    * 100
).round(2)

customer_performance = customer_performance.sort_values(
    "Revenue",
    ascending=False
)

customer_performance.head(10)

      CustomerKey     Revenue  GrossProfit  Orders  Units_Sold  ProfitMargin_%
419         11433  12407.9545    5074.7670       6          13           40.90
424         11439  12015.4029    4971.5382       6          19           41.38
233         11241  11330.4494    4780.9088       7          33           42.20
403         11417  11085.7504    4650.9561       7          26           41.95
406         11420  11022.4002    4611.7390       7          23           41.84
234         11242  10852.0340    4505.9653       7          14           41.52
2188        13263  10436.5079    4246.1004       4          18           40.69
1604        12655  10394.9836    4222.8261       4          12           40.62
411         11425  10391.4304    4403.1453       6          22           42.37
1580        12631  10331.7349    4200.6771       4          17           40.66

In [17]:
customer_purchase_frequency = (
    customer_performance
    .groupby("Orders")
    .agg(
        Customers=("CustomerKey", "count"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
    .reset_index()
)

customer_purchase_frequency

    Orders  Customers       Revenue   GrossProfit
0        1      11559  6.959545e+06  2.916182e+06
1        2       4692  1.280473e+07  5.327556e+06
2        3        983  4.534985e+06  1.946484e+06
3        4        114  4.666682e+05  1.972613e+05
4        5         27  1.083174e+04  6.452887e+03
5        6          5  5.428541e+04  2.268738e+04
6        7          4  4.429063e+04  1.854957e+04
7       13          2  1.896128e+03  1.056098e+03
8       15          8  7.471996e+03  4.207046e+03
9       16          6  5.761964e+03  3.206506e+03
10      17          2  2.337901e+03  1.320246e+03
11      23          1  1.111226e+03  6.488828e+02
12      24          6  9.038810e+03  5.350321e+03
13      25          2  3.330639e+03  1.912925e+03
14      26          5  8.303992e+03  4.840454e+03

In [18]:
customer_segments = (
    customer_performance
    .assign(
        CustomerType=lambda x: x["Orders"].apply(
            lambda orders: "One-Time" if orders == 1 else "Repeat"
        )
    )
    .groupby("CustomerType")
    .agg(
        Customers=("CustomerKey", "count"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("Orders", "sum"),
        Units_Sold=("Units_Sold", "sum")
    )
    .reset_index()
)

customer_segments["Customer_%"] = (
    customer_segments["Customers"]
    / customer_segments["Customers"].sum()
    * 100
).round(2)

customer_segments["Revenue_%"] = (
    customer_segments["Revenue"]
    / customer_segments["Revenue"].sum()
    * 100
).round(2)

customer_segments["Profit_%"] = (
    customer_segments["GrossProfit"]
    / customer_segments["GrossProfit"].sum()
    * 100
).round(2)

customer_segments

,CustomerType,Customers,Revenue,GrossProfit,Orders,Units_Sold,Customer_%,Revenue_%,Profit_%
0,One-Time,11559,6.959545e+06,2.916182e+06,11559,43591,66.37,27.93,27.89
1,Repeat,5857,1.795504e+07,7.541534e+06,13605,40583,33.63,72.07,72.11

In [19]:
customer_segments["Avg_Revenue_per_Customer"] = (
    customer_segments["Revenue"]
    / customer_segments["Customers"]
).round(2)

customer_segments["Avg_Profit_per_Customer"] = (
    customer_segments["GrossProfit"]
    / customer_segments["Customers"]
).round(2)

customer_segments[
    [
        "CustomerType",
        "Customers",
        "Revenue",
        "GrossProfit",
        "Avg_Revenue_per_Customer",
        "Avg_Profit_per_Customer"
    ]
]

,CustomerType,Customers,Revenue,GrossProfit,Avg_Revenue_per_Customer,Avg_Profit_per_Customer
0,One-Time,11559,6.959545e+06,2.916182e+06,602.09,252.29
1,Repeat,5857,1.795504e+07,7.541534e+06,3065.57,1287.61

In [21]:
customer_analysis = customer_performance.merge(
    customers[["CustomerKey", "AnnualIncome"]],
    on="CustomerKey",
    how="left"
)

customer_analysis["IncomeBand"] = pd.cut(
    customer_analysis["AnnualIncome"],
    bins=[0, 50000, 100000, 150000, float("inf")],
    labels=["Low", "Medium", "High", "Very High"]
)

income_performance = (
    customer_analysis
    .groupby("IncomeBand", observed=False)
    .agg(
        Customers=("CustomerKey", "count"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("Orders", "sum"),
        Units_Sold=("Units_Sold", "sum")
    )
    .reset_index()
)

income_performance["Avg_Revenue_per_Customer"] = (
    income_performance["Revenue"] /
    income_performance["Customers"]
).round(2)

income_performance["ProfitMargin_%"] = (
    income_performance["GrossProfit"] /
    income_performance["Revenue"] * 100
).round(2)

income_performance

NameError: name 'customers' is not defined

In [22]:
customers = pd.read_csv(
    cleaned_path / "Customers_Cleaned.csv"
)

print(customers.shape)
print(customers[["CustomerKey", "AnnualIncome"]].head())

(18148, 13)
   CustomerKey  AnnualIncome
0        11000         90000
1        11001         60000
2        11002         60000
3        11003         70000
4        11004         80000

In [23]:
customer_analysis = customer_performance.merge(
    customers[["CustomerKey", "AnnualIncome"]],
    on="CustomerKey",
    how="left"
)

customer_analysis["IncomeBand"] = pd.cut(
    customer_analysis["AnnualIncome"],
    bins=[0, 50000, 100000, 150000, float("inf")],
    labels=["Low", "Medium", "High", "Very High"]
)

income_performance = (
    customer_analysis
    .groupby("IncomeBand", observed=False)
    .agg(
        Customers=("CustomerKey", "count"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("Orders", "sum"),
        Units_Sold=("Units_Sold", "sum")
    )
    .reset_index()
)

income_performance["Avg_Revenue_per_Customer"] = (
    income_performance["Revenue"] /
    income_performance["Customers"]
).round(2)

income_performance["ProfitMargin_%"] = (
    income_performance["GrossProfit"] /
    income_performance["Revenue"] * 100
).round(2)

income_performance

,IncomeBand,Customers,Revenue,GrossProfit,Orders,Units_Sold,Avg_Revenue_per_Customer,ProfitMargin_%
0,Low,8118,9.708023e+06,4.047838e+06,11106,37311,1195.86,41.70
1,Medium,7758,1.202623e+07,5.064536e+06,11581,38381,1550.17,42.11
2,High,1343,2.742681e+06,1.160761e+06,2161,7342,2042.20,42.32
3,Very High,197,4.376484e+05,1.845799e+05,316,1140,2221.57,42.18

In [24]:
territories_clean = pd.read_csv(
    cleaned_path / "Territories_Cleaned.csv"
)

sales_territory = sales_category.merge(
    territories_clean,
    left_on="TerritoryKey",
    right_on="SalesTerritoryKey",
    how="left"
)

territory_performance = (
    sales_territory
    .groupby(["Country", "Region"])
    .agg(
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum"),
        Orders=("OrderNumber", "nunique"),
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

territory_performance["ProfitMargin_%"] = (
    territory_performance["GrossProfit"]
    / territory_performance["Revenue"] * 100
).round(2)

territory_performance = territory_performance.sort_values(
    "Revenue",
    ascending=False
)

territory_performance

,Country,Region,Revenue,GrossProfit,Orders,Units_Sold,ProfitMargin_%
0,Australia,Australia,7.416456e+06,3.077023e+06,6060,17951,41.49
9,United States,Southwest,4.822795e+06,2.040345e+06,4992,17191,42.31
7,United States,Northwest,3.095074e+06,1.314751e+06,3675,12513,42.48
4,United Kingdom,United Kingdom,2.902562e+06,1.214774e+06,2771,9694,41.85
3,Germany,Germany,2.524680e+06,1.054186e+06,2294,7950,41.76
2,France,France,2.362643e+06,9.893461e+05,2315,7862,41.87
1,Canada,Canada,1.769246e+06,7.578442e+05,3024,10894,42.83
8,United States,Southeast,1.158562e+04,5.133288e+03,14,49,44.31
6,United States,Northeast,6.401568e+03,2.874582e+03,10,40,44.90
5,United States,Central,3.143060e+03,1.437441e+03,9,30,45.73

In [25]:
customer_yearly = (
    sales_category
    .groupby("Year")
    .agg(
        Customers=("CustomerKey", "nunique"),
        Orders=("OrderNumber", "nunique"),
        Revenue=("Revenue", "sum"),
        GrossProfit=("GrossProfit", "sum")
    )
    .reset_index()
)

customer_yearly["Customer_Growth_%"] = (
    customer_yearly["Customers"]
    .pct_change() * 100
).round(2)

customer_yearly["Revenue_per_Customer"] = (
    customer_yearly["Revenue"]
    / customer_yearly["Customers"]
).round(2)

customer_yearly

,Year,Customers,Orders,Revenue,GrossProfit,Customer_Growth_%,Revenue_per_Customer
0,2015,2630,2630,6.404934e+06,2.601602e+06,NaN,2435.34
1,2016,9133,10695,9.324204e+06,3.967084e+06,247.26,1020.94
2,2017,10502,11839,9.185449e+06,3.889029e+06,14.99,874.64

In [26]:
customers_2015 = set(
    sales_category.loc[sales_category["Year"] == 2015, "CustomerKey"]
)

customers_2016 = set(
    sales_category.loc[sales_category["Year"] == 2016, "CustomerKey"]
)

customers_2017 = set(
    sales_category.loc[sales_category["Year"] == 2017, "CustomerKey"]
)

retention = pd.DataFrame({
    "Year": [2016, 2017],
    "Previous_Year_Customers": [
        len(customers_2015),
        len(customers_2016)
    ],
    "Returning_Customers": [
        len(customers_2015 & customers_2016),
        len(customers_2016 & customers_2017)
    ]
})

retention["Retention_Rate_%"] = (
    retention["Returning_Customers"]
    / retention["Previous_Year_Customers"]
    * 100
).round(2)

retention

   Year  Previous_Year_Customers  Returning_Customers  Retention_Rate_%
0  2016                     2630                 1204             45.78
1  2017                     9133                 2397             26.25

In [27]:
returns_clean = pd.read_csv(
    cleaned_path / "Returns_Cleaned.csv"
)

print(returns_clean.shape)
print(returns_clean.columns)
print(returns_clean.head())

FileNotFoundError: [Errno 2] No such file or directory: '..\\data\\cleaned\\Returns_Cleaned.csv'

In [28]:
returns = pd.read_csv(
    raw_path / "Returns.csv"
)

print("Shape:", returns.shape)
print("\nColumns:")
print(returns.columns.tolist())

print("\nData Types:")
print(returns.dtypes)

print("\nMissing Values:")
print(returns.isnull().sum())

print("\nFirst 5 Rows:")
print(returns.head())

NameError: name 'raw_path' is not defined

In [29]:
from pathlib import Path
import pandas as pd

raw_path = Path("../data/raw")
cleaned_path = Path("../data/cleaned")

returns = pd.read_csv(
    raw_path / "Returns.csv"
)

print("Shape:", returns.shape)
print("\nColumns:")
print(returns.columns.tolist())

print("\nData Types:")
print(returns.dtypes)

print("\nMissing Values:")
print(returns.isnull().sum())

print("\nFirst 5 Rows:")
print(returns.head())

Shape: (1809, 4)

Columns:
['ReturnDate', 'TerritoryKey', 'ProductKey', 'ReturnQuantity']

Data Types:
ReturnDate        object
TerritoryKey       int64
ProductKey         int64
ReturnQuantity     int64
dtype: object

Missing Values:
ReturnDate        0
TerritoryKey      0
ProductKey        0
ReturnQuantity    0
dtype: int64

First 5 Rows:
  ReturnDate  TerritoryKey  ProductKey  ReturnQuantity
0  1/18/2015             9         312               1
1  1/18/2015            10         310               1
2  1/21/2015             8         346               1
3  1/22/2015             4         311               1
4   2/2/2015             6         312               1

In [30]:
returns["ReturnDate"] = pd.to_datetime(
    returns["ReturnDate"],
    format="%m/%d/%Y"
)

print("Return date range:")
print(returns["ReturnDate"].min(), "to", returns["ReturnDate"].max())

print("\nReturn quantity:")
print("Minimum:", returns["ReturnQuantity"].min())
print("Maximum:", returns["ReturnQuantity"].max())
print("Zero quantities:", (returns["ReturnQuantity"] == 0).sum())
print("Negative quantities:", (returns["ReturnQuantity"] < 0).sum())

print("\nDuplicate rows:", returns.duplicated().sum())

print("\nUnique products returned:", returns["ProductKey"].nunique())
print("Unique territories:", returns["TerritoryKey"].nunique())

print("\nTerritory keys:")
print(sorted(returns["TerritoryKey"].unique()))

print("\nProduct key validity:")
print(
    "Invalid ProductKeys:",
    (~returns["ProductKey"].isin(products_clean["ProductKey"])).sum()
)

print("\nTerritory key validity:")
print(
    "Invalid TerritoryKeys:",
    (~returns["TerritoryKey"].isin(territories_clean["SalesTerritoryKey"])).sum()
)

Return date range:
2015-01-18 00:00:00 to 2017-06-30 00:00:00

Return quantity:
Minimum: 1
Maximum: 2
Zero quantities: 0
Negative quantities: 0

Duplicate rows: 0

Unique products returned: 124
Unique territories: 8

Territory keys:
[np.int64(1), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)]

Product key validity:
Invalid ProductKeys: 0

Territory key validity:
Invalid TerritoryKeys: 0

In [1]:
from pathlib import Path
import pandas as pd

raw_path = Path("../data/raw")
cleaned_path = Path("../data/cleaned")

returns = pd.read_csv(
    raw_path / "Returns.csv"
)

returns["ReturnDate"] = pd.to_datetime(
    returns["ReturnDate"],
    format="%m/%d/%Y"
)

returns_cleaned_file = cleaned_path / "Returns_Cleaned.csv"

returns.to_csv(
    returns_cleaned_file,
    index=False
)

print("Saved:", returns_cleaned_file)
print("Shape:", returns.shape)

Saved: ..\data\cleaned\Returns_Cleaned.csv
Shape: (1809, 4)

In [2]:
total_returned_units = returns["ReturnQuantity"].sum()
total_sold_units = sales_all["OrderQuantity"].sum()

overall_return_rate = (
    total_returned_units / total_sold_units * 100
)

print("Total returned units:", total_returned_units)
print("Total sold units:", total_sold_units)
print("Overall return rate:", round(overall_return_rate, 2), "%")

NameError: name 'sales_all' is not defined

In [3]:
from pathlib import Path
import pandas as pd

cleaned_path = Path("../data/cleaned")

sales_all = pd.read_csv(
    cleaned_path / "Sales_All_Cleaned.csv"
)

sales_all["OrderDate"] = pd.to_datetime(
    sales_all["OrderDate"],
    format="%Y-%m-%d"
)

print("Shape:", sales_all.shape)
print("Total sold units:", sales_all["OrderQuantity"].sum())

Shape: (56046, 9)
Total sold units: 84174

In [4]:
total_returned_units = returns["ReturnQuantity"].sum()
total_sold_units = sales_all["OrderQuantity"].sum()

overall_return_rate = (
    total_returned_units / total_sold_units * 100
)

print("Total returned units:", total_returned_units)
print("Total sold units:", total_sold_units)
print("Overall return rate:", round(overall_return_rate, 2), "%")

Total returned units: 1828
Total sold units: 84174
Overall return rate: 2.17 %

In [5]:
product_sales = (
    sales_all
    .groupby("ProductKey")
    .agg(
        Units_Sold=("OrderQuantity", "sum"),
        Orders=("OrderNumber", "nunique")
    )
    .reset_index()
)

product_returns = (
    returns
    .groupby("ProductKey")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

product_return_rate = product_sales.merge(
    product_returns,
    on="ProductKey",
    how="left"
)

product_return_rate["Units_Returned"] = (
    product_return_rate["Units_Returned"]
    .fillna(0)
)

product_return_rate["Return_Rate_%"] = (
    product_return_rate["Units_Returned"]
    / product_return_rate["Units_Sold"]
    * 100
).round(2)

product_return_rate = product_return_rate.merge(
    products_clean[["ProductKey", "ProductName"]],
    on="ProductKey",
    how="left"
)

product_return_rate = product_return_rate.sort_values(
    "Return_Rate_%",
    ascending=False
)

product_return_rate.head(15)

NameError: name 'products_clean' is not defined

In [6]:
products_clean = pd.read_csv(
    cleaned_path / "Products_Cleaned.csv"
)

print("Shape:", products_clean.shape)
print(products_clean[["ProductKey", "ProductName"]].head())

Shape: (293, 11)
   ProductKey              ProductName
0         214    Sport-100 Helmet, Red
1         215  Sport-100 Helmet, Black
2         218   Mountain Bike Socks, M
3         219   Mountain Bike Socks, L
4         220   Sport-100 Helmet, Blue

In [7]:
product_sales = (
    sales_all
    .groupby("ProductKey")
    .agg(
        Units_Sold=("OrderQuantity", "sum"),
        Orders=("OrderNumber", "nunique")
    )
    .reset_index()
)

product_returns = (
    returns
    .groupby("ProductKey")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

product_return_rate = product_sales.merge(
    product_returns,
    on="ProductKey",
    how="left"
)

product_return_rate["Units_Returned"] = (
    product_return_rate["Units_Returned"]
    .fillna(0)
)

product_return_rate["Return_Rate_%"] = (
    product_return_rate["Units_Returned"]
    / product_return_rate["Units_Sold"]
    * 100
).round(2)

product_return_rate = product_return_rate.merge(
    products_clean[["ProductKey", "ProductName"]],
    on="ProductKey",
    how="left"
)

product_return_rate = product_return_rate.sort_values(
    "Return_Rate_%",
    ascending=False
)

product_return_rate.head(15)

,ProductKey,Units_Sold,Orders,Units_Returned,Return_Rate_%,ProductName
18,330,51,51,6.0,11.76,"Road-650 Red, 52"
27,346,24,24,2.0,8.33,"Mountain-100 Silver, 44"
103,577,96,96,8.0,8.33,"Touring-2000 Blue, 46"
126,600,41,41,3.0,7.32,"Mountain-500 Black, 52"
31,350,31,31,2.0,6.45,"Mountain-100 Black, 44"
91,565,54,54,3.0,5.56,"Touring-3000 Blue, 54"
32,351,36,36,2.0,5.56,"Mountain-100 Black, 48"
17,328,75,75,4.0,5.33,"Road-650 Red, 48"
119,593,38,38,2.0,5.26,"Mountain-500 Silver, 44"
14,322,39,39,2.0,5.13,"Road-650 Red, 60"
55,471,157,157,8.0,5.10,"Classic Vest, S"
60,476,334,334,17.0,5.09,"Women's Mountain Shorts, L"
94,568,59,59,3.0,5.08,"Touring-3000 Yellow, 44"
9,311,139,139,7.0,5.04,"Road-150 Red, 44"
88,562,146,146,7.0,4.79,"Touring-1000 Yellow, 50"

In [8]:
high_volume_returns = (
    product_return_rate[
        product_return_rate["Units_Sold"] >= 100
    ]
    .sort_values("Return_Rate_%", ascending=False)
)

high_volume_returns[
    [
        "ProductKey",
        "ProductName",
        "Units_Sold",
        "Units_Returned",
        "Return_Rate_%",
        "Orders"
    ]
].head(15)

,ProductKey,ProductName,Units_Sold,Units_Returned,Return_Rate_%,Orders
55,471,"Classic Vest, S",157,8.0,5.10,157
60,476,"Women's Mountain Shorts, L",334,17.0,5.09,334
9,311,"Road-150 Red, 44",139,7.0,5.04,139
88,562,"Touring-1000 Yellow, 50",146,7.0,4.79,146
10,312,"Road-150 Red, 48",179,8.0,4.47,179
58,474,"Women's Mountain Shorts, S",283,12.0,4.24,283
128,605,"Road-750 Black, 48",355,15.0,4.23,355
114,588,"Mountain-400-W Silver, 40",126,5.0,3.97,126
73,489,"Short-Sleeve Classic Jersey, M",379,15.0,3.96,379
41,370,"Road-250 Red, 52",128,5.0,3.91,128
107,581,"Road-350-W Yellow, 42",233,9.0,3.86,233
56,472,"Classic Vest, M",182,7.0,3.85,182
81,537,HL Mountain Tire,1305,49.0,3.75,1305
49,385,"Road-550-W Yellow, 42",296,11.0,3.72,296
5,229,"Long-Sleeve Logo Jersey, M",408,15.0,3.68,408

In [1]:
from pathlib import Path
import pandas as pd

cleaned_path = Path("../data/cleaned")

# Sales
sales_all = pd.read_csv(
    cleaned_path / "Sales_All_Cleaned.csv"
)
sales_all["OrderDate"] = pd.to_datetime(
    sales_all["OrderDate"],
    format="%Y-%m-%d"
)

# Products
products_clean = pd.read_csv(
    cleaned_path / "Products_Cleaned.csv"
)

# Product hierarchy
subcategories_clean = pd.read_csv(
    cleaned_path / "Product-Subcategories_Cleaned.csv"
)

categories_clean = pd.read_csv(
    cleaned_path / "Product-Categories_Cleaned.csv"
)

# Returns
returns = pd.read_csv(
    cleaned_path / "Returns_Cleaned.csv"
)
returns["ReturnDate"] = pd.to_datetime(
    returns["ReturnDate"],
    format="%Y-%m-%d"
)

print("Sales:", sales_all.shape)
print("Products:", products_clean.shape)
print("Subcategories:", subcategories_clean.shape)
print("Categories:", categories_clean.shape)
print("Returns:", returns.shape)

Sales: (56046, 9)
Products: (293, 11)
Subcategories: (37, 3)
Categories: (4, 2)
Returns: (1809, 4)

In [2]:
sales_product = sales_all.merge(
    products_clean[
        [
            "ProductKey",
            "ProductName",
            "ProductSubcategoryKey",
            "ProductCost",
            "ProductPrice"
        ]
    ],
    on="ProductKey",
    how="left"
)

sales_product["Revenue"] = (
    sales_product["OrderQuantity"]
    * sales_product["ProductPrice"]
)

sales_product["Cost"] = (
    sales_product["OrderQuantity"]
    * sales_product["ProductCost"]
)

sales_product["GrossProfit"] = (
    sales_product["Revenue"]
    - sales_product["Cost"]
)

sales_product["Month"] = sales_product["OrderDate"].dt.month

In [3]:
sales_category = sales_product.merge(
    subcategories_clean[
        [
            "ProductSubcategoryKey",
            "SubcategoryName",
            "ProductCategoryKey"
        ]
    ],
    on="ProductSubcategoryKey",
    how="left"
)

sales_category = sales_category.merge(
    categories_clean[
        ["ProductCategoryKey", "CategoryName"]
    ],
    on="ProductCategoryKey",
    how="left"
)

print(sales_category.shape)

(56046, 20)

In [4]:
# Returned units by category
category_returns = (
    returns
    .merge(
        products_clean[
            ["ProductKey", "ProductSubcategoryKey"]
        ],
        on="ProductKey",
        how="left"
    )
    .merge(
        subcategories_clean[
            ["ProductSubcategoryKey", "ProductCategoryKey"]
        ],
        on="ProductSubcategoryKey",
        how="left"
    )
    .merge(
        categories_clean[
            ["ProductCategoryKey", "CategoryName"]
        ],
        on="ProductCategoryKey",
        how="left"
    )
    .groupby("CategoryName")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

# Sold units by category
category_sold = (
    sales_category
    .groupby("CategoryName")
    .agg(
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

# Combine sales and returns
category_return_rate = category_sold.merge(
    category_returns,
    on="CategoryName",
    how="left"
)

category_return_rate["Units_Returned"] = (
    category_return_rate["Units_Returned"]
    .fillna(0)
)

# Calculate return rate
category_return_rate["Return_Rate_%"] = (
    category_return_rate["Units_Returned"]
    / category_return_rate["Units_Sold"]
    * 100
).round(2)

# Highest return rate first
category_return_rate.sort_values(
    "Return_Rate_%",
    ascending=False
)

  CategoryName  Units_Sold  Units_Returned  Return_Rate_%
1        Bikes       13929             429           3.08
2     Clothing       12436             269           2.16
0  Accessories       57809            1130           1.95

In [5]:
subcategory_returns = (
    returns
    .merge(
        products_clean[
            ["ProductKey", "ProductSubcategoryKey"]
        ],
        on="ProductKey",
        how="left"
    )
    .merge(
        subcategories_clean[
            ["ProductSubcategoryKey", "SubcategoryName"]
        ],
        on="ProductSubcategoryKey",
        how="left"
    )
    .groupby("SubcategoryName")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

subcategory_sold = (
    sales_category
    .groupby("SubcategoryName")
    .agg(
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

subcategory_return_rate = subcategory_sold.merge(
    subcategory_returns,
    on="SubcategoryName",
    how="left"
)

subcategory_return_rate["Units_Returned"] = (
    subcategory_return_rate["Units_Returned"]
    .fillna(0)
)

subcategory_return_rate["Return_Rate_%"] = (
    subcategory_return_rate["Units_Returned"]
    / subcategory_return_rate["Units_Sold"]
    * 100
).round(2)

subcategory_return_rate.sort_values(
    "Return_Rate_%",
    ascending=False
)

      SubcategoryName  Units_Sold  Units_Returned  Return_Rate_%
12             Shorts         944              40           4.24
16              Vests         521              19           3.65
8     Hydration Packs         695              25           3.60
1         Bike Stands         234               8           3.42
15      Touring Bikes        2124              70           3.30
11         Road Bikes        7099             223           3.14
7             Helmets        6034             188           3.12
9             Jerseys        3113              93           2.99
10     Mountain Bikes        4706             136           2.89
0          Bike Racks         302               8           2.65
13              Socks        1063              22           2.07
2   Bottles and Cages       15106             288           1.91
6              Gloves        2644              49           1.85
14    Tires and Tubes       29772             534           1.79
4            Cleaners        1706              25           1.47
5             Fenders        3960              54           1.36
3                Caps        4151              46           1.11

In [6]:
# Sold units by year
yearly_sold = (
    sales_all
    .groupby("Year")
    .agg(
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

# Returned units by year
returns["Year"] = returns["ReturnDate"].dt.year

yearly_returned = (
    returns
    .groupby("Year")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

# Combine sales and returns
yearly_return_rate = yearly_sold.merge(
    yearly_returned,
    on="Year",
    how="left"
)

yearly_return_rate["Units_Returned"] = (
    yearly_return_rate["Units_Returned"]
    .fillna(0)
)

# Calculate return rate
yearly_return_rate["Return_Rate_%"] = (
    yearly_return_rate["Units_Returned"]
    / yearly_return_rate["Units_Sold"]
    * 100
).round(2)

yearly_return_rate

   Year  Units_Sold  Units_Returned  Return_Rate_%
0  2015        2630              86           3.27
1  2016       36230             770           2.13
2  2017       45314             972           2.15

In [7]:
# Extract month from return date
returns["Month"] = returns["ReturnDate"].dt.month

# Sold units by year and month
monthly_sold = (
    sales_all
    .groupby(["Year", "Month"])
    .agg(
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

# Returned units by year and month
monthly_returned = (
    returns
    .groupby(["Year", "Month"])
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

# Combine sales and returns
monthly_return_rate = monthly_sold.merge(
    monthly_returned,
    on=["Year", "Month"],
    how="left"
)

monthly_return_rate["Units_Returned"] = (
    monthly_return_rate["Units_Returned"]
    .fillna(0)
)

# Calculate return rate
monthly_return_rate["Return_Rate_%"] = (
    monthly_return_rate["Units_Returned"]
    / monthly_return_rate["Units_Sold"]
    * 100
).round(2)

monthly_return_rate.sort_values(
    ["Year", "Month"]
)

KeyError: 'Month'

In [8]:
sales_all["Month"] = sales_all["OrderDate"].dt.month

print(
    sales_all[["OrderDate", "Year", "Month"]].head()
)

   OrderDate  Year  Month
0 2015-01-01  2015      1
1 2015-01-01  2015      1
2 2015-01-01  2015      1
3 2015-01-01  2015      1
4 2015-01-02  2015      1

In [9]:
monthly_sold = (
    sales_all
    .groupby(["Year", "Month"])
    .agg(
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

monthly_returned = (
    returns
    .groupby(["Year", "Month"])
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

monthly_return_rate = monthly_sold.merge(
    monthly_returned,
    on=["Year", "Month"],
    how="left"
)

monthly_return_rate["Units_Returned"] = (
    monthly_return_rate["Units_Returned"]
    .fillna(0)
)

monthly_return_rate["Return_Rate_%"] = (
    monthly_return_rate["Units_Returned"]
    / monthly_return_rate["Units_Sold"]
    * 100
).round(2)

monthly_return_rate.sort_values(
    ["Year", "Month"]
)

    Year  Month  Units_Sold  Units_Returned  Return_Rate_%
0   2015      1         184               4           2.17
1   2015      2         165               4           2.42
2   2015      3         198               9           4.55
3   2015      4         204              14           6.86
4   2015      5         206              11           5.34
5   2015      6         212               4           1.89
6   2015      7         247               3           1.21
7   2015      8         278               6           2.16
8   2015      9         196               2           1.02
9   2015     10         223              11           4.93
10  2015     11         191               5           2.62
11  2015     12         326              13           3.99
12  2016      1         242               8           3.31
13  2016      2         267               8           3.00
14  2016      3         266               8           3.01
15  2016      4         290               5           1.72
16  2016      5         329              10           3.04
17  2016      6         312               8           2.56
18  2016      7        1954              45           2.30
19  2016      8        5958             120           2.01
20  2016      9        5970             122           2.04
21  2016     10        6387             137           2.14
22  2016     11        6332             136           2.15
23  2016     12        7923             163           2.06
24  2017      1        7020             158           2.25
25  2017      2        6828             154           2.26
26  2017      3        7327             160           2.18
27  2017      4        7680             164           2.14
28  2017      5        8199             169           2.06
29  2017      6        8260             167           2.02

In [10]:
print("Return date range:")
print(returns["ReturnDate"].min(), "to", returns["ReturnDate"].max())

print("\nSales order date range:")
print(sales_all["OrderDate"].min(), "to", sales_all["OrderDate"].max())

print("\nReturn dates matching sales order dates:")
print(
    returns["ReturnDate"]
    .isin(sales_all["OrderDate"])
    .sum()
)

print(
    "Total return records:",
    len(returns)
)

Return date range:
2015-01-18 00:00:00 to 2017-06-30 00:00:00

Sales order date range:
2015-01-01 00:00:00 to 2017-06-30 00:00:00

Return dates matching sales order dates:
1809
Total return records: 1809

In [11]:
# Returned units by territory
territory_returns = (
    returns
    .groupby("TerritoryKey")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

# Sold units by territory
territory_sold = (
    sales_all
    .groupby("TerritoryKey")
    .agg(
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

# Combine sales and returns
territory_return_rate = territory_sold.merge(
    territory_returns,
    on="TerritoryKey",
    how="left"
)

territory_return_rate["Units_Returned"] = (
    territory_return_rate["Units_Returned"]
    .fillna(0)
)

# Calculate return rate
territory_return_rate["Return_Rate_%"] = (
    territory_return_rate["Units_Returned"]
    / territory_return_rate["Units_Sold"]
    * 100
).round(2)

# Add geographic information
territory_return_rate = territory_return_rate.merge(
    territories_clean,
    left_on="TerritoryKey",
    right_on="SalesTerritoryKey",
    how="left"
)

territory_return_rate = territory_return_rate[
    [
        "TerritoryKey",
        "Region",
        "Country",
        "Continent",
        "Units_Sold",
        "Units_Returned",
        "Return_Rate_%"
    ]
]

territory_return_rate.sort_values(
    "Return_Rate_%",
    ascending=False
)

NameError: name 'territories_clean' is not defined

In [12]:
territories_clean = pd.read_csv(
    cleaned_path / "Territories_Cleaned.csv"
)

print(territories_clean.shape)
print(territories_clean)

(10, 4)
   SalesTerritoryKey          Region         Country      Continent
0                  1       Northwest   United States  North America
1                  2       Northeast   United States  North America
2                  3         Central   United States  North America
3                  4       Southwest   United States  North America
4                  5       Southeast   United States  North America
5                  6          Canada          Canada  North America
6                  7          France          France         Europe
7                  8         Germany         Germany         Europe
8                  9       Australia       Australia        Pacific
9                 10  United Kingdom  United Kingdom         Europe

In [13]:
territory_returns = (
    returns
    .groupby("TerritoryKey")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

territory_sold = (
    sales_all
    .groupby("TerritoryKey")
    .agg(
        Units_Sold=("OrderQuantity", "sum")
    )
    .reset_index()
)

territory_return_rate = territory_sold.merge(
    territory_returns,
    on="TerritoryKey",
    how="left"
)

territory_return_rate["Units_Returned"] = (
    territory_return_rate["Units_Returned"]
    .fillna(0)
)

territory_return_rate["Return_Rate_%"] = (
    territory_return_rate["Units_Returned"]
    / territory_return_rate["Units_Sold"]
    * 100
).round(2)

territory_return_rate = territory_return_rate.merge(
    territories_clean,
    left_on="TerritoryKey",
    right_on="SalesTerritoryKey",
    how="left"
)

territory_return_rate = territory_return_rate[
    [
        "TerritoryKey",
        "Region",
        "Country",
        "Continent",
        "Units_Sold",
        "Units_Returned",
        "Return_Rate_%"
    ]
]

territory_return_rate.sort_values(
    "Return_Rate_%",
    ascending=False
)

,TerritoryKey,Region,Country,Continent,Units_Sold,Units_Returned,Return_Rate_%
6,7,France,France,Europe,7862,186.0,2.37
8,9,Australia,Australia,Pacific,17951,404.0,2.25
5,6,Canada,Canada,North America,10894,238.0,2.18
0,1,Northwest,United States,North America,12513,270.0,2.16
3,4,Southwest,United States,North America,17191,362.0,2.11
9,10,United Kingdom,United Kingdom,Europe,9694,204.0,2.10
7,8,Germany,Germany,Europe,7950,163.0,2.05
4,5,Southeast,United States,North America,49,1.0,2.04
1,2,Northeast,United States,North America,40,0.0,0.00
2,3,Central,United States,North America,30,0.0,0.00

In [14]:
product_return_impact = product_return_rate.merge(
    products_clean[
        [
            "ProductKey",
            "ProductCost",
            "ProductPrice"
        ]
    ],
    on="ProductKey",
    how="left"
)

product_return_impact["GrossProfit_Lost"] = (
    product_return_impact["Units_Returned"]
    * (
        product_return_impact["ProductPrice"]
        - product_return_impact["ProductCost"]
    )
)

product_return_impact = product_return_impact.sort_values(
    "GrossProfit_Lost",
    ascending=False
)

product_return_impact[
    [
        "ProductKey",
        "ProductName",
        "Units_Sold",
        "Units_Returned",
        "Return_Rate_%",
        "GrossProfit_Lost"
    ]
].head(15)

NameError: name 'product_return_rate' is not defined

In [15]:
product_sales = (
    sales_all
    .groupby("ProductKey")
    .agg(
        Units_Sold=("OrderQuantity", "sum"),
        Orders=("OrderNumber", "nunique")
    )
    .reset_index()
)

product_returns = (
    returns
    .groupby("ProductKey")
    .agg(
        Units_Returned=("ReturnQuantity", "sum")
    )
    .reset_index()
)

product_return_rate = product_sales.merge(
    product_returns,
    on="ProductKey",
    how="left"
)

product_return_rate["Units_Returned"] = (
    product_return_rate["Units_Returned"]
    .fillna(0)
)

product_return_rate["Return_Rate_%"] = (
    product_return_rate["Units_Returned"]
    / product_return_rate["Units_Sold"]
    * 100
).round(2)

product_return_rate = product_return_rate.merge(
    products_clean[["ProductKey", "ProductName"]],
    on="ProductKey",
    how="left"
)

print(product_return_rate.shape)

(130, 6)

In [16]:
product_return_impact = product_return_rate.merge(
    products_clean[
        [
            "ProductKey",
            "ProductCost",
            "ProductPrice"
        ]
    ],
    on="ProductKey",
    how="left"
)

product_return_impact["GrossProfit_Lost"] = (
    product_return_impact["Units_Returned"]
    * (
        product_return_impact["ProductPrice"]
        - product_return_impact["ProductCost"]
    )
)

product_return_impact = product_return_impact.sort_values(
    "GrossProfit_Lost",
    ascending=False
)

product_return_impact[
    [
        "ProductKey",
        "ProductName",
        "Units_Sold",
        "Units_Returned",
        "Return_Rate_%",
        "GrossProfit_Lost"
    ]
].head(15)

,ProductKey,ProductName,Units_Sold,Units_Returned,Return_Rate_%,GrossProfit_Lost
37,360,"Mountain-200 Black, 42",602,21.0,3.49,19809.0522
38,362,"Mountain-200 Black, 46",606,18.0,2.97,16979.1876
33,352,"Mountain-200 Silver, 38",586,17.0,2.90,16210.5829
34,354,"Mountain-200 Silver, 42",547,15.0,2.74,14303.4555
36,358,"Mountain-200 Black, 38",569,15.0,2.64,14149.3230
35,356,"Mountain-200 Silver, 46",571,12.0,2.10,11442.7644
10,312,"Road-150 Red, 48",179,8.0,4.47,11255.8064
9,311,"Road-150 Red, 44",139,7.0,5.04,9848.8306
42,371,"Road-250 Red, 58",303,11.0,3.63,9469.6657
45,377,"Road-250 Black, 52",316,11.0,3.48,9469.6657
43,373,"Road-250 Black, 44",263,9.0,3.42,7747.9083
11,313,"Road-150 Red, 52",168,5.0,2.98,7034.8790
12,314,"Road-150 Red, 56",157,5.0,3.18,7034.8790
44,375,"Road-250 Black, 48",294,8.0,2.72,6887.0296
88,562,"Touring-1000 Yellow, 50",146,7.0,4.79,6314.9247

In [17]:
# Final project-level KPIs

total_revenue = sales_category["Revenue"].sum()
total_cost = sales_category["Cost"].sum()
total_profit = sales_category["GrossProfit"].sum()
total_orders = sales_category["OrderNumber"].nunique()
total_units = sales_category["OrderQuantity"].sum()
total_customers = sales_category["CustomerKey"].nunique()

total_returned_units = returns["ReturnQuantity"].sum()
overall_return_rate = total_returned_units / total_units * 100

overall_profit_margin = total_profit / total_revenue * 100

final_kpis = pd.DataFrame({
    "KPI": [
        "Total Revenue",
        "Total Cost",
        "Gross Profit",
        "Profit Margin",
        "Total Orders",
        "Units Sold",
        "Unique Customers",
        "Units Returned",
        "Return Rate"
    ],
    "Value": [
        total_revenue,
        total_cost,
        total_profit,
        overall_profit_margin,
        total_orders,
        total_units,
        total_customers,
        total_returned_units,
        overall_return_rate
    ]
})

final_kpis

                KPI         Value
0     Total Revenue  2.491459e+07
1        Total Cost  1.445687e+07
2      Gross Profit  1.045772e+07
3     Profit Margin  4.197427e+01
4      Total Orders  2.516400e+04
5        Units Sold  8.417400e+04
6  Unique Customers  1.741600e+04
7    Units Returned  1.828000e+03
8       Return Rate  2.171692e+00

In [18]:
analysis_columns = [
    "OrderDate",
    "OrderNumber",
    "ProductKey",
    "CustomerKey",
    "TerritoryKey",
    "OrderLineItem",
    "OrderQuantity",
    "Year",
    "ProductName",
    "ProductSubcategoryKey",
    "SubcategoryName",
    "ProductCategoryKey",
    "CategoryName",
    "ProductCost",
    "ProductPrice",
    "Revenue",
    "Cost",
    "GrossProfit"
]

sales_analysis = sales_category[analysis_columns].copy()

analysis_file = cleaned_path / "Sales_Analysis_Ready.csv"
sales_analysis.to_csv(analysis_file, index=False)

print("Saved:", analysis_file)
print("Shape:", sales_analysis.shape)
print("\nColumns:")
print(sales_analysis.columns.tolist())

Saved: ..\data\cleaned\Sales_Analysis_Ready.csv
Shape: (56046, 18)

Columns:
['OrderDate', 'OrderNumber', 'ProductKey', 'CustomerKey', 'TerritoryKey', 'OrderLineItem', 'OrderQuantity', 'Year', 'ProductName', 'ProductSubcategoryKey', 'SubcategoryName', 'ProductCategoryKey', 'CategoryName', 'ProductCost', 'ProductPrice', 'Revenue', 'Cost', 'GrossProfit']

In [1]:
# RFM Analysis - Step 1
# Create the base RFM table

import pandas as pd

# Load analysis-ready sales data
sales_rfm = pd.read_csv(
    "../data/cleaned/Sales_Analysis_Ready.csv"
)

# Convert OrderDate to datetime
sales_rfm["OrderDate"] = pd.to_datetime(
    sales_rfm["OrderDate"],
    format="%Y-%m-%d"
)

# Use the latest transaction date as the analysis reference date
reference_date = sales_rfm["OrderDate"].max()

print("Reference Date:", reference_date)

# Create customer-level RFM metrics
rfm = sales_rfm.groupby("CustomerKey").agg(
    Recency=("OrderDate", lambda x: (reference_date - x.max()).days),
    Frequency=("OrderNumber", "nunique"),
    Monetary=("Revenue", "sum")
).reset_index()

# Display first few records
rfm.head()

Reference Date: 2017-06-30 00:00:00

   CustomerKey  Recency  Frequency   Monetary
0        11000      238          2  4656.3896
1        11001       18          2  2821.2122
2        11002      307          2  4466.8124
3        11003      231          2  4532.9866
4        11004      240          2  4568.0838

In [2]:
rfm.shape

(17416, 4)

In [3]:
rfm.head()

   CustomerKey  Recency  Frequency   Monetary
0        11000      238          2  4656.3896
1        11001       18          2  2821.2122
2        11002      307          2  4466.8124
3        11003      231          2  4532.9866
4        11004      240          2  4568.0838

In [4]:
# RFM Analysis - Step 2
# Create Recency, Frequency and Monetary scores

# Recency:
# Lower recency is better, so the scoring is reversed.
rfm["R_Score"] = pd.qcut(
    rfm["Recency"],
    5,
    labels=[5, 4, 3, 2, 1]
).astype(int)

# Frequency:
# Higher frequency is better.
rfm["F_Score"] = pd.qcut(
    rfm["Frequency"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

# Monetary:
# Higher monetary value is better.
rfm["M_Score"] = pd.qcut(
    rfm["Monetary"].rank(method="first"),
    5,
    labels=[1, 2, 3, 4, 5]
).astype(int)

# Combined RFM score
rfm["RFM_Score"] = (
    rfm["R_Score"]
    + rfm["F_Score"]
    + rfm["M_Score"]
)

rfm.head()

,CustomerKey,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score
0,11000,238,2,4656.3896,2,4,5,11
1,11001,18,2,2821.2122,5,4,5,14
2,11002,307,2,4466.8124,1,4,5,10
3,11003,231,2,4532.9866,2,4,5,11
4,11004,240,2,4568.0838,2,4,5,11

In [5]:
# RFM Analysis - Step 3
# Create customer segments

def assign_rfm_segment(row):
    r = row["R_Score"]
    f = row["F_Score"]
    m = row["M_Score"]

    if r >= 4 and f >= 4 and m >= 4:
        return "Champions"

    elif r >= 3 and f >= 4 and m >= 3:
        return "Loyal Customers"

    elif r >= 4 and f <= 2 and m <= 3:
        return "New Customers"

    elif r <= 2 and f >= 3 and m >= 3:
        return "At Risk"

    elif r <= 2 and f <= 2 and m >= 3:
        return "Can't Lose Them"

    elif r <= 2 and f <= 2 and m <= 2:
        return "Lost Customers"

    else:
        return "Potential Loyalists"


rfm["Customer_Segment"] = rfm.apply(
    assign_rfm_segment,
    axis=1
)

# Check segment distribution
rfm["Customer_Segment"].value_counts()

Customer_Segment
Potential Loyalists    6013
At Risk                2752
Champions              1968
Loyal Customers        1869
New Customers          1808
Lost Customers         1788
Can't Lose Them        1218
Name: count, dtype: int64

In [6]:
# RFM Analysis - Step 4
# Create segment-level business summary

rfm_summary = (
    rfm.groupby("Customer_Segment")
    .agg(
        Customers=("CustomerKey", "count"),
        Avg_Recency=("Recency", "mean"),
        Avg_Frequency=("Frequency", "mean"),
        Total_Revenue=("Monetary", "sum"),
        Avg_Revenue_Per_Customer=("Monetary", "mean")
    )
    .reset_index()
)

# Add revenue share
rfm_summary["Revenue_Share_%"] = (
    rfm_summary["Total_Revenue"]
    / rfm_summary["Total_Revenue"].sum()
    * 100
)

# Round values for readability
rfm_summary["Avg_Recency"] = rfm_summary["Avg_Recency"].round(1)
rfm_summary["Avg_Frequency"] = rfm_summary["Avg_Frequency"].round(2)
rfm_summary["Total_Revenue"] = rfm_summary["Total_Revenue"].round(2)
rfm_summary["Avg_Revenue_Per_Customer"] = (
    rfm_summary["Avg_Revenue_Per_Customer"].round(2)
)
rfm_summary["Revenue_Share_%"] = (
    rfm_summary["Revenue_Share_%"].round(2)
)

# Sort by revenue
rfm_summary = rfm_summary.sort_values(
    "Total_Revenue",
    ascending=False
)

rfm_summary

,Customer_Segment,Customers,Avg_Recency,Avg_Frequency,Total_Revenue,Avg_Revenue_Per_Customer,Revenue_Share_%
2,Champions,1968,52.4,2.44,7898376.80,4013.40,31.70
0,At Risk,2752,293.2,1.64,7724407.24,2806.83,31.00
4,Loyal Customers,1869,108.5,2.34,4356298.82,2330.82,17.48
6,Potential Loyalists,6013,126.0,1.11,3207073.67,533.36,12.87
1,Can't Lose Them,1218,264.6,1.00,1278431.44,1049.62,5.13
5,New Customers,1808,56.0,1.00,342776.14,189.59,1.38
3,Lost Customers,1788,257.4,1.00,107222.71,59.97,0.43

In [7]:
# RFM Analysis - Step 5
# Save customer-level RFM dataset

rfm.to_csv(
    "../data/cleaned/RFM_Customer_Segmentation.csv",
    index=False
)

print("RFM dataset saved successfully.")
print("Shape:", rfm.shape)

RFM dataset saved successfully.
Shape: (17416, 9)

In [8]:
# RFM Analysis - Step 6
# Final segment summary

rfm_final_summary = (
    rfm.groupby("Customer_Segment")
    .agg(
        Customers=("CustomerKey", "count"),
        Avg_Recency_Days=("Recency", "mean"),
        Avg_Frequency=("Frequency", "mean"),
        Total_Revenue=("Monetary", "sum"),
        Avg_Revenue_Per_Customer=("Monetary", "mean")
    )
    .reset_index()
)

rfm_final_summary["Customer_Share_%"] = (
    rfm_final_summary["Customers"]
    / rfm_final_summary["Customers"].sum()
    * 100
)

rfm_final_summary["Revenue_Share_%"] = (
    rfm_final_summary["Total_Revenue"]
    / rfm_final_summary["Total_Revenue"].sum()
    * 100
)

rfm_final_summary = rfm_final_summary.round(2)

rfm_final_summary = rfm_final_summary.sort_values(
    "Total_Revenue",
    ascending=False
)

rfm_final_summary

,Customer_Segment,Customers,Avg_Recency_Days,Avg_Frequency,Total_Revenue,Avg_Revenue_Per_Customer,Customer_Share_%,Revenue_Share_%
2,Champions,1968,52.40,2.44,7898376.80,4013.40,11.30,31.70
0,At Risk,2752,293.21,1.64,7724407.24,2806.83,15.80,31.00
4,Loyal Customers,1869,108.48,2.34,4356298.82,2330.82,10.73,17.48
6,Potential Loyalists,6013,125.97,1.11,3207073.67,533.36,34.53,12.87
1,Can't Lose Them,1218,264.62,1.00,1278431.44,1049.62,6.99,5.13
5,New Customers,1808,56.03,1.00,342776.14,189.59,10.38,1.38
3,Lost Customers,1788,257.42,1.00,107222.71,59.97,10.27,0.43